"""Generate PEP 561 stubs for `triton` and `triton.language`.

Reads the AST of the language and runtime sources. Never imports Triton, so it
needs no built `_C` extension.

    python python/triton/tools/generate_type_stubs.py            # write
    python python/triton/tools/generate_type_stubs.py --check    # verify
    python python/triton/tools/generate_type_stubs.py --stats    # coverage
"""

from __future__ import annotations

import argparse
import ast
import sys
from collections.abc import Collection, Sequence
from dataclasses import dataclass, field
from pathlib import Path

HEADER = ("# AUTOGENERATED by pre-commit; edit the sources or\n"
          "# python/triton/tools/generate_type_stubs.py instead.")

PACKAGE = Path(__file__).resolve().parents[1]

# Parameters the compiler injects; user code never passes them.
INJECTED_PARAMS = {"_semantic", "_generator", "_ns"}

# `__str__` and `__repr__` are redundant in a stub: `object` already declares
# them (ruff PYI029). `__eq__` and `__ne__` must accept `object` rather than
# the source's untyped parameter (ruff PYI032).
REDUNDANT_DUNDERS = {"__str__", "__repr__"}
OBJECT_PARAM_DUNDERS = {"__eq__", "__ne__"}

# Dunders whose return type the default "returns a value" rule gets wrong.
DUNDER_RETURNS = {
    "__str__": "str",
    "__repr__": "str",
    "__hash__": "int",
    "__index__": "int",
    "__len__": "int",
    "__bool__": "bool",
    "__eq__": "bool",
    "__ne__": "bool",
    "__iter__": "Any",
    "__next__": "Any",
    "__enter__": "Any",
    "__exit__": "None",
    "__init__": "None",
    "__new__": "Any",
    "__post_init__": "None",
}

# Overrides that cannot be well-formed, keyed "ClassName.method".
# tensor comparisons yield a mask, not a bool. The dtype entries are source
# inconsistencies: with_element_ty renames its parameter in the subclass, and
# is_block/is_ptr/is_const are staticmethods overridden as instance methods.
OVERRIDE_IGNORES = {
    "tensor.__eq__",
    "tensor.__ne__",
    "block_type.is_block",
    "block_type.with_element_ty",
    "pointer_type.is_ptr",
    "pointer_type.is_const",
}

BUILTIN_NAMES = {
    "Any", "None", "int", "str", "bool", "float", "object", "type", "tuple", "list", "dict", "set", "bytes", "complex",
    "Callable"
}


@dataclass
class Target:
    """One generated stub: where it goes and what it is built from."""

    name: str
    output: Path
    init_py: Path
    sources: tuple[Path, ...]
    submodules: tuple[str, ...] = ()
    default_return: str = "Any"
    return_overrides: dict[str, str] = field(default_factory=dict)
    # Keyed "ClassName.method"; consulted before `return_overrides`.
    method_return_overrides: dict[str, str] = field(default_factory=dict)
    symbol_overrides: dict[str, str] = field(default_factory=dict)


LANGUAGE = Target(
    name="triton.language",
    output=PACKAGE / "language/__init__.pyi",
    init_py=PACKAGE / "language/__init__.py",
    sources=tuple(PACKAGE / "language" / f for f in ("core.py", "standard.py", "math.py", "random.py")),
    submodules=("extra", "math"),
    # Nearly every language builtin returns a tensor.
    default_return="tensor",
    return_overrides={
        "program_id": "tensor",
        "num_programs": "tensor",
        "static_assert": "None",
        "static_print": "None",
        "device_print": "None",
        "device_assert": "None",
        "debug_barrier": "None",
        "store": "None",
        "atomic_poll": "None",
        "cdiv": "int",
        "next_power_of_2": "int",
        "with_element_ty": "dtype",
    },
    method_return_overrides={
        "tensor.__eq__": "tensor",
        "tensor.__ne__": "tensor",
    },
    symbol_overrides={
        # constexpr is a class at runtime, but as an annotation it means any
        # compile-time value; callers pass ints, strings and dtypes.
        "constexpr": "constexpr: TypeAlias = Any  # noqa: PYI042",
        "constexpr_type": "constexpr_type: TypeAlias = Any  # noqa: PYI042",
    },
)

ROOT = Target(
    name="triton",
    output=PACKAGE / "__init__.pyi",
    init_py=PACKAGE / "__init__.py",
    sources=(
        PACKAGE / "runtime/jit.py",
        PACKAGE / "runtime/autotuner.py",
        PACKAGE / "runtime/errors.py",
        PACKAGE / "runtime/interpreter.py",
        PACKAGE / "compiler/errors.py",
        PACKAGE / "compiler/compiler.py",
        PACKAGE / "errors.py",
    ),
    submodules=("language", "runtime", "testing", "tools"),
    return_overrides={"cdiv": "int", "next_power_of_2": "int"},
    symbol_overrides={
        # kernel[grid](...) takes the kernel's parameters plus backend launch
        # options (num_warps, num_stages, ...), passed directly or merged in
        # from a Config. ParamSpec cannot express "these plus extra keywords".
        "KernelInterface": ("class KernelInterface:\n"
                            "    def __getitem__(self, grid: Any) -> Callable[..., Any]: ...\n"
                            "    def run(self, *args: Any, grid: Any, warmup: bool,"
                            " **kwargs: Any) -> Any: ..."),
    },
)

TARGETS = (LANGUAGE, ROOT)

# Builtins that triton.language re-defines; see sanitize().
SHADOWED = {"tuple", "range", "slice", "abs", "min", "max", "sum"}


def parse(path: Path) -> ast.Module:
    return ast.parse(path.read_text(encoding="utf-8"), filename=str(path))


def dunder_all(path: Path) -> list[str]:
    for node in parse(path).body:
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == "__all__":
                    return list(ast.literal_eval(node.value))
    raise ValueError(f"{path} does not define __all__")


def decorator_names(node: ast.FunctionDef | ast.ClassDef) -> set[str]:
    """Bare names of a definition's decorators, ignoring any module prefix."""
    names = set()
    for dec in node.decorator_list:
        expr = dec.func if isinstance(dec, ast.Call) else dec
        if isinstance(expr, ast.Name):
            names.add(expr.id)
        elif isinstance(expr, ast.Attribute):
            names.add(expr.attr)
    return names


def base_name(node: ast.expr) -> str | None:
    """Name of a base class, unwrapping generic subscripts like `Foo[T]`."""
    if isinstance(node, ast.Subscript):
        node = node.value
    return node.id if isinstance(node, ast.Name) else None


def always_raises(node: ast.FunctionDef) -> bool:
    """Whether the body only raises. Such bodies are placeholders; the code
    generator supplies the real behaviour."""
    return bool(node.body) and isinstance(node.body[-1], (ast.Raise, ast.Assert))


def returns_a_value(node: ast.FunctionDef) -> bool:
    for child in ast.walk(node):
        if isinstance(child, ast.Return) and child.value is not None:
            return True
    return False


def sanitize(annotation: str, known: set[str], shadowed: Collection[str] = ()) -> str:
    """Replace annotations naming types the stub does not define with `Any`.

    `shadowed` holds builtins that triton.language redefines; subscripting one
    would resolve to the non-generic Triton class.
    """
    try:
        tree = ast.parse(annotation, mode="eval")
    except SyntaxError:
        return "Any"
    for node in ast.walk(tree):
        if isinstance(node, ast.Attribute):
            return "Any"
        if isinstance(node, ast.Subscript) and isinstance(node.value, ast.Name):
            if node.value.id in shadowed:
                return "Any"
        if isinstance(node, ast.Name) and node.id not in known:
            return "Any"
    return annotation


def render_annotation(node: ast.expr | None, known: set[str]) -> str:
    return sanitize(ast.unparse(node), known, SHADOWED) if node is not None else "Any"


def render_signature(fn: ast.FunctionDef, known: set[str], *, drop_self: bool = False, drop_first: bool = False) -> str:
    args = fn.args
    positional = [a for a in args.posonlyargs + args.args if a.arg not in INJECTED_PARAMS]
    if drop_self and positional and (drop_first or positional[0].arg in ("self", "cls")):
        positional = positional[1:]

    # Defaults bind to the tail of posonly+args, so align them by offset.
    all_positional = args.posonlyargs + args.args
    offset = len(all_positional) - len(args.defaults)
    defaults = {all_positional[offset + i].arg for i in range(len(args.defaults))}

    parts = ["self"] if drop_self else []
    for a in positional:
        suffix = " = ..." if a.arg in defaults else ""
        parts.append(f"{a.arg}: {render_annotation(a.annotation, known)}{suffix}")
    if args.vararg:
        parts.append(f"*{args.vararg.arg}: "
                     f"{render_annotation(args.vararg.annotation, known)}")
    elif args.kwonlyargs:
        parts.append("*")
    for a, d in zip(args.kwonlyargs, args.kw_defaults):
        if a.arg in INJECTED_PARAMS:
            continue
        suffix = " = ..." if d is not None else ""
        parts.append(f"{a.arg}: {render_annotation(a.annotation, known)}{suffix}")
    if args.kwarg:
        parts.append(f"**{args.kwarg.arg}: "
                     f"{render_annotation(args.kwarg.annotation, known)}")
    return ", ".join(parts)


def render_return(fn: ast.FunctionDef, known: set[str], target: Target, cls: str | None = None) -> str:
    if fn.returns is not None:
        return sanitize(ast.unparse(fn.returns), known, SHADOWED)
    if cls is not None and f"{cls}.{fn.name}" in target.method_return_overrides:
        return target.method_return_overrides[f"{cls}.{fn.name}"]
    if fn.name in target.return_overrides:
        return target.return_overrides[fn.name]
    if fn.name in DUNDER_RETURNS:
        return DUNDER_RETURNS[fn.name]
    if fn.name.startswith("is_"):
        return "bool"
    if returns_a_value(fn) or always_raises(fn):
        return target.default_return
    return "None"


def instance_attributes(cls: ast.ClassDef, known: set[str]) -> list[str]:
    """Public `self.x = ...` bindings in __init__, which are part of the API."""
    out: dict[str, str] = {}
    for node in cls.body:
        if not (isinstance(node, ast.FunctionDef) and node.name == "__init__"):
            continue
        for stmt in ast.walk(node):
            targets: list[ast.expr] = []
            annotation = None
            if isinstance(stmt, ast.Assign):
                # `self.a, self.b = ...` and `self.a = self.b = ...` both bind.
                for t in stmt.targets:
                    targets.extend(t.elts if isinstance(t, (ast.Tuple, ast.List)) else [t])
            elif isinstance(stmt, ast.AnnAssign):
                targets, annotation = [stmt.target], stmt.annotation
            for target in targets:
                if (isinstance(target, ast.Attribute) and isinstance(target.value, ast.Name)
                        and target.value.id == "self" and not target.attr.startswith("_")):
                    out.setdefault(target.attr, render_annotation(annotation, known))
    return [f"    {name}: {ann}" for name, ann in sorted(out.items())]


def render_class(cls: ast.ClassDef, members: dict[str, ast.FunctionDef], known: set[str], target: Target) -> list[str]:
    bases = [n for n in (base_name(b) for b in cls.bases) if n is not None and n in known]
    header = f"class {cls.name}({', '.join(bases)}):" if bases else f"class {cls.name}:"
    lines = [header]

    body = instance_attributes(cls, known)
    for node in cls.body:
        if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            if not node.target.id.startswith("_"):
                body.append(f"    {node.target.id}: "
                            f"{render_annotation(node.annotation, known)}")
        elif isinstance(node, ast.FunctionDef):
            if node.name.startswith("_") and not node.name.startswith("__"):
                continue
            if node.name in REDUNDANT_DUNDERS:
                continue
            if node.name in OBJECT_PARAM_DUNDERS:
                ret = render_return(node, known, target, cls.name)
                ign = ("  # type: ignore[override]" if f"{cls.name}.{node.name}" in OVERRIDE_IGNORES else "")
                body.append(f"    def {node.name}(self, other: object) -> {ret}: ...{ign}")
                continue
            decs = decorator_names(node)
            prefix = ""
            for marker in ("property", "staticmethod", "classmethod"):
                if marker in decs:
                    prefix = f"    @{marker}\n"
                    break
            sig = render_signature(node, known, drop_self="staticmethod" not in decs)
            ignore = ("  # type: ignore[override]" if f"{cls.name}.{node.name}" in OVERRIDE_IGNORES else "")
            body.append(f"{prefix}    def {node.name}({sig}) -> "
                        f"{render_return(node, known, target, cls.name)}: ...{ignore}")

    # @_tensor_member_fn promotes free functions to tensor methods. An explicit
    # definition in the class body wins; the promoted function's first
    # parameter is the receiver.
    if cls.name == "tensor":
        defined = {n.name for n in cls.body if isinstance(n, ast.FunctionDef)}
        for name, fn in sorted(members.items()):
            if name in defined:
                continue
            sig = render_signature(fn, known, drop_self=True, drop_first=True)
            body.append(f"    def {name}({sig}) -> "
                        f"{render_return(fn, known, target)}: ...")

    lines.extend(body or ["    ..."])
    return lines


def collect(target: Target) -> tuple[dict[str, ast.AST], dict[str, list[ast.FunctionDef]], dict[str, ast.FunctionDef]]:
    """Map each public name to its definition, its `@overload` set, and the
    `@_tensor_member_fn` functions."""
    definitions: dict[str, ast.AST] = {}
    overloads: dict[str, list[ast.FunctionDef]] = {}
    members: dict[str, ast.FunctionDef] = {}
    for path in target.sources:
        if not path.exists():
            continue
        for node in parse(path).body:
            if not isinstance(node, (ast.FunctionDef, ast.ClassDef)):
                continue
            definitions.setdefault(node.name, node)
            if isinstance(node, ast.FunctionDef):
                if "overload" in decorator_names(node):
                    overloads.setdefault(node.name, []).append(node)
                if "_tensor_member_fn" in decorator_names(node):
                    members.setdefault(node.name, node)
    return definitions, overloads, members


def generate(target: Target) -> str:
    exported = dunder_all(target.init_py)
    definitions, overloads, members = collect(target)

    # Emit base classes outside __all__ too, or subclasses lose inherited
    # members.
    extra_bases: list[str] = []
    pending = [n for n in exported if isinstance(definitions.get(n), ast.ClassDef)]
    seen = set(pending)
    while pending:
        cls = definitions.get(pending.pop())
        if not isinstance(cls, ast.ClassDef):
            continue
        for base in cls.bases:
            name = base_name(base)
            if name is not None and name not in seen and name in definitions:
                seen.add(name)
                extra_bases.append(name)
                pending.append(name)

    known = set(exported) | set(extra_bases) | BUILTIN_NAMES

    lines: list[str] = []
    for sub in target.submodules:
        if sub in exported:
            lines.append(f"from . import {sub} as {sub}")
    lines.append("")

    classes = ([n for n in reversed(extra_bases) if isinstance(definitions.get(n), ast.ClassDef)] +
               [n for n in exported if isinstance(definitions.get(n), ast.ClassDef)])
    emitted = set()
    for name in classes:
        if name in emitted:
            continue
        emitted.add(name)
        if name in target.symbol_overrides:
            lines.extend([target.symbol_overrides[name], ""])
            continue
        cls = definitions[name]
        assert isinstance(cls, ast.ClassDef)
        lines.extend(render_class(cls, members, known, target))
        lines.append("")

    for name in exported:
        if name in emitted:
            continue
        if name in target.symbol_overrides:
            lines.append(target.symbol_overrides[name])
        elif name in overloads:
            for fn in overloads[name]:
                lines.append("@overload")
                lines.append(f"def {name}({render_signature(fn, known)}) -> "
                             f"{render_return(fn, known, target)}: ...")
        elif isinstance(defn := definitions.get(name), ast.FunctionDef):
            lines.append(f"def {name}({render_signature(defn, known)}) -> "
                         f"{render_return(defn, known, target)}: ...")

    unresolved = [
        n for n in exported if n not in definitions and n not in target.symbol_overrides and n not in target.submodules
    ]
    if unresolved:
        lines += [
            "", "# Exported names with no definition in the scanned sources;", "# mostly dtype aliases and re-exports."
        ]
        lines += [f"{name}: Any" for name in unresolved]
    lines.append("")

    # Only the imports the body references, for ruff F401.
    body = "\n".join(lines)
    imports = []
    if "Callable" in body:
        imports.append("from collections.abc import Callable")
    typing_names = [n for n in ("Any", "TypeAlias", "overload") if n in body]
    if typing_names:
        imports.append(f"from typing import {', '.join(sorted(typing_names))}")
    content = "\n".join([HEADER, "", *imports, "", body])
    # A generator bug that emits unparseable output would otherwise only
    # surface when something tried to read the stub.
    ast.parse(content, filename=str(target.output))
    return content


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if a stub is out of date")
    parser.add_argument("--stats", action="store_true", help="report coverage of __all__")
    args = parser.parse_args(argv)

    stale = False
    for target in TARGETS:
        content = generate(target)
        if args.stats:
            exported = dunder_all(target.init_py)
            covered = sum(1 for n in exported if f"def {n}(" in content or f"class {n}" in content
                          or f"\n{n}: " in content or f"\n{n} = " in content or f"import {n} as {n}" in content)
            pct = 100 * covered // len(exported)
            print(f"{target.name:16} {covered}/{len(exported)} of __all__ ({pct}%)")
        if args.check:
            if not target.output.exists() or target.output.read_text(encoding="utf-8") != content:
                print(f"{target.output} is out of date; run "
                      f"python python/triton/tools/{Path(__file__).name}", file=sys.stderr)
                stale = True
        else:
            # Write only on change; a pre-commit hook must not touch files it
            # leaves unchanged.
            if not target.output.exists() or target.output.read_text(encoding="utf-8") != content:
                target.output.write_text(content, encoding="utf-8", newline="\n")
                print(f"wrote {target.output}")
    return 1 if stale else 0


if __name__ == "__main__":
    raise SystemExit(main())
