#ifndef LOWERINGDIALECTPLUGIN_LOWERINGDIALECTPLUGINTYPES_H
#define LOWERINGDIALECTPLUGIN_LOWERINGDIALECTPLUGINTYPES_H

#include "mlir/IR/BuiltinTypes.h"

#define GET_TYPEDEF_CLASSES
#include "LoweringDialectPlugin/LoweringDialectPluginOpsTypes.h.inc"

#endif // LOWERINGDIALECTPLUGIN_LOWERINGDIALECTPLUGINTYPES_H
