[pytest]
addopts = --tb=short
markers =
    interpreter: indicate whether interpreter supports the test
    enable_warmup: test supports shape-only Triton compilation before execution
    disable_warmup: exclude an exceptional case from module-level warmup
python_files = test_*.py *_test.py tutorials/*.py examples/*.py
