# Autogenerated from /Users/andrew/zzCoding-play/triton/test/lit.site.cfg.py.in
# Do not edit!

# Allow generated file to be relocatable.
import os
import platform
def path(p):
    if not p: return ''
    # Follows lit.util.abs_path_preserve_drive, which cannot be imported here.
    if platform.system() == 'Windows':
        return os.path.abspath(os.path.join(os.path.dirname(__file__), p))
    else:
        return os.path.realpath(os.path.join(os.path.dirname(__file__), p))


import sys

config.triton_obj_root = "/Users/andrew/zzCoding-play/triton/build_unittest"
config.llvm_src_root = ""
config.llvm_obj_root = "/opt/homebrew/Cellar/llvm/20.1.8"
config.llvm_tools_dir = "/opt/homebrew/Cellar/llvm/20.1.8/bin"
config.llvm_lib_dir = "/opt/homebrew/Cellar/llvm/20.1.8/lib"
config.llvm_shlib_dir = ""
config.llvm_shlib_ext = ".dylib"
config.llvm_exe_ext = ""
config.lit_tools_dir = ""
config.mlir_binary_dir = ""
config.python_executable = ""
config.enable_bindings_python = 0


import lit.llvm
lit.llvm.initialize(lit_config, config)

# Let the main config do the real work
lit_config.load_config(config, "/Users/andrew/zzCoding-play/triton/test/lit.cfg.py")
