#ifndef TRITON_DIALECT_TRITONGPU_IR_ATTRIBUTES_H_
#define TRITON_DIALECT_TRITONGPU_IR_ATTRIBUTES_H_

#define GET_ATTRDEF_CLASSES
#include "triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.h.inc"

#endif // TRITON_DIALECT_TRITONGPU_IR_ATTRIBUTES_H_
