if(EXISTS "/Users/andrew/zzCoding-play/triton/build_unittest/unittest/Metal/PipelineConcurrency[1]_tests.cmake")
  include("/Users/andrew/zzCoding-play/triton/build_unittest/unittest/Metal/PipelineConcurrency[1]_tests.cmake")
else()
  add_test(PipelineConcurrency_NOT_BUILT PipelineConcurrency_NOT_BUILT)
endif()
