blank_issues_enabled: true
contact_links:
  - name: Community help
    url: https://discord.gg/gpumode
    about: GPU-mode discord community has a triton channel which is a great resource for help writing/learning triton
