if(EXISTS "/Users/andrew/zzCoding-play/triton/build_unittest/unittest/Analysis/TestTritonAnalysis[1]_tests.cmake")
  include("/Users/andrew/zzCoding-play/triton/build_unittest/unittest/Analysis/TestTritonAnalysis[1]_tests.cmake")
else()
  add_test(TestTritonAnalysis_NOT_BUILT TestTritonAnalysis_NOT_BUILT)
endif()
