if(EXISTS "/Users/andrew/zzCoding-play/triton/build_unittest_sanitize/asan/unittest/Dialect/TritonGPU/Dialect[1]_tests.cmake")
  include("/Users/andrew/zzCoding-play/triton/build_unittest_sanitize/asan/unittest/Dialect/TritonGPU/Dialect[1]_tests.cmake")
else()
  add_test(Dialect_NOT_BUILT Dialect_NOT_BUILT)
endif()
