// RUN: triton-opt --split-input-file %s | FileCheck %s
// RUN: triton-opt --split-input-file %s --tritongpu-optimize-one-hot-xor-reduction | FileCheck %s --check-prefix=ONE-HOT

// CHECK: #[[$WMMA_GEN1:.*]] = #ttg.amd_wmma<{{.*}}version = 1{{.*}}>
// CHECK: #[[$WMMA_GEN2:.*]] = #ttg.amd_wmma<{{.*}}version = 2{{.*}}>
// CHECK: #[[$WMMA_GEN3:.*]] = #ttg.amd_wmma<{{.*}}version = 3{{.*}}>
#blocked = #ttg.blocked<{sizePerThread = [2, 2], threadsPerWarp = [4, 8], warpsPerCTA = [1, 1], order = [1, 0]}>

module attributes {"ttg.target" = "cuda:0", "ttg.num-ctas" = 1 : i32, "ttg.num-warps" = 1 : i32, "ttg.threads-per-warp" = 32 : i32} {
  // CHECK-LABEL: wmma_layout
  tt.func @wmma_layout(%0: tensor<16x16xf16, #blocked>) {
    %1 = ttg.convert_layout %0 : tensor<16x16xf16, #blocked> -> tensor<16x16xf16, #ttg.amd_wmma<{version = 1, ctaLayout = {register = [], warp = []}}>>
    // CHECK:  %{{.+}} = ttg.convert_layout %{{.+}} : tensor<16x16xf16, #{{.+}}> -> tensor<16x16xf16, #[[$WMMA_GEN1]]>
    tt.return
  }

  // CHECK-LABEL: wmma_dot_op_layout
  tt.func @wmma_dot_op_layout(%0: tensor<16x16xf16, #ttg.dot_op<{opIdx = 1, parent = #blocked}>>) {
    %1 = ttg.convert_layout %0 : tensor<16x16xf16, #ttg.dot_op<{opIdx = 1, parent = #blocked}>> -> tensor<16x16xf16, #ttg.dot_op<{opIdx = 1, parent = #ttg.amd_wmma<{version = 1, ctaLayout = {register = [], warp = []}}>, kWidth = 16}>>
    // CHECK:  %{{.+}} = ttg.convert_layout %{{.+}} : tensor<16x16xf16, #ttg.dot_op<{opIdx = 1, parent = #{{.+}}}>> -> tensor<16x16xf16, #ttg.dot_op<{opIdx = 1, parent = #[[$WMMA_GEN1]], kWidth = 16}>>
    tt.return
  }

  // CHECK-LABEL: wmma_gen2_layout
  tt.func @wmma_gen2_layout(%0: tensor<16x16xf16, #blocked>) {
    %1 = ttg.convert_layout %0 : tensor<16x16xf16, #blocked> -> tensor<16x16xf16, #ttg.amd_wmma<{version = 2, ctaLayout = {warp = []}}>>
    // CHECK:  %{{.+}} = ttg.convert_layout %{{.+}} : tensor<16x16xf16, #{{.+}}> -> tensor<16x16xf16, #[[$WMMA_GEN2]]>
    tt.return
  }

  // CHECK-LABEL: wmma_gen2_dot_op_layout
  tt.func @wmma_gen2_dot_op_layout(%0: tensor<16x16xf16, #ttg.dot_op<{opIdx = 1, parent = #blocked}>>) {
    %1 = ttg.convert_layout %0 : tensor<16x16xf16, #ttg.dot_op<{opIdx = 1, parent = #blocked}>> -> tensor<16x16xf16, #ttg.dot_op<{opIdx = 1, parent = #ttg.amd_wmma<{version = 2, ctaLayout = {warp = []}}>, kWidth = 8}>>
    // CHECK:  %{{.+}} = ttg.convert_layout %{{.+}} : tensor<16x16xf16, #ttg.dot_op<{opIdx = 1, parent = #{{.+}}}>> -> tensor<16x16xf16, #ttg.dot_op<{opIdx = 1, parent = #[[$WMMA_GEN2]], kWidth = 8}>>
    tt.return
  }

  // CHECK-LABEL: wmma_gen3_layout
  tt.func @wmma_gen3_layout(%0: tensor<16x16xf32, #blocked>) {
    %1 = ttg.convert_layout %0 : tensor<16x16xf32, #blocked> -> tensor<16x16xf32, #ttg.amd_wmma<{version = 3, ctaLayout = {warp = []}, instrShape = [16, 16, 32]}>>
    // CHECK:  %{{.+}} = ttg.convert_layout %{{.+}} : tensor<16x16xf32, #{{.+}}> -> tensor<16x16xf32, #[[$WMMA_GEN3]]>
    tt.return
  }

  // CHECK-LABEL: wmma_gen3_dot_op_layout
  tt.func @wmma_gen3_dot_op_layout(%0: tensor<16x32xbf16, #ttg.dot_op<{opIdx = 0, parent = #blocked}>>) {
    %1 = ttg.convert_layout %0 : tensor<16x32xbf16, #ttg.dot_op<{opIdx = 0, parent = #blocked}>> -> tensor<16x32xbf16, #ttg.dot_op<{opIdx = 0, parent = #ttg.amd_wmma<{version = 3, ctaLayout = {warp = []}, instrShape = [16, 16, 32]}>, kWidth = 8}>>
    // CHECK:  %{{.+}} = ttg.convert_layout %{{.+}} : tensor<16x32xbf16, #ttg.dot_op<{opIdx = 0, parent = #{{.+}}}>> -> tensor<16x32xbf16, #ttg.dot_op<{opIdx = 0, parent = #[[$WMMA_GEN3]], kWidth = 8}>>
    tt.return
  }
}
// -----

#blocked= #ttg.blocked<{sizePerThread = [1, 1], threadsPerWarp = [8, 4], warpsPerCTA = [4, 1], order = [1, 0]}>
// CHECK: #[[$LINEAR:.*]] = #ttg.linear<{{.*}}>

module attributes {"ttg.target" = "cuda:0", "ttg.num-ctas" = 1 : i32, "ttg.num-warps" = 4 : i32, "ttg.threads-per-warp" = 32 : i32} {
  // CHECK-LABEL: @blocked_to_linear
  tt.func @blocked_to_linear(%input: tensor<32x4xi8, #blocked>) {
    // The layout is the basic layout generated by DecomposeScaledBlocked
    %output = ttg.convert_layout %input {allocation.offset = 0 : i32} : tensor<32x4xi8, #blocked> -> tensor<32x4xi8, #ttg.linear<{register = [], lane = [[0, 1], [1, 0], [2, 0], [4, 0], [8, 0]], warp = [[0, 0], [16, 0]], block = []}>>
    // CHECK:  %{{.+}} = ttg.convert_layout %{{.+}} : tensor<32x4xi8, #blocked> -> tensor<32x4xi8, #[[$LINEAR]]>
    tt.return
  }
}

// -----

#shared0 = #ttg.nvmma_shared<{swizzlingByteWidth = 32, transposed = false, elementBitWidth = 16}>
#smem = #ttg.shared_memory
module attributes {"ttg.target" = "cuda:0", "ttg.num-ctas" = 1 : i32, "ttg.num-warps" = 1 : i32, "ttg.threads-per-warp" = 32 : i32} {
  // CHECK-LABEL: memdesc
  // CHECK-SAME: !ttg.memdesc<1x64x16xf16, #{{.+}}>
  tt.func @memdesc(%d : !ttg.memdesc<1x64x16xf16, #shared0, #smem>) {
    tt.return
  }

  // CHECK-LABEL: memdesc_with_alloc_shape
  // CHECK-SAME: !ttg.memdesc<64x16xf16, #{{.+}}, mutable, 2x64x16>
  tt.func @memdesc_with_alloc_shape(%d : !ttg.memdesc<64x16xf16, #shared0, #smem, mutable, 2x64x16>){
    tt.return
  }
}

// -----

#shared = #ttg.nvmma_shared<{swizzlingByteWidth = 64, transposed = false, elementBitWidth = 16}>
#smem = #ttg.shared_memory
module attributes {"ttg.target" = "cuda:0", "ttg.num-ctas" = 1 : i32, "ttg.num-warps" = 1 : i32, "ttg.threads-per-warp" = 32 : i32} {
  // CHECK-LABEL: @multibuffer_subview_unaligned_pipeline_offset
  tt.func @multibuffer_subview_unaligned_pipeline_offset(%arg0: !ttg.memdesc<5x8x32xf16, #shared, #smem>) {
    // CHECK: ttg.memdesc_subslice %{{.*}}[2, 0, 0]
    %0 = ttg.memdesc_subslice %arg0 [2, 0, 0] : !ttg.memdesc<5x8x32xf16, #shared, #smem> -> !ttg.memdesc<3x8x32xf16, #shared, #smem, 5x8x32>
    tt.return
  }
}

// -----

#shared_a = #ttg.nvmma_shared<{swizzlingByteWidth = 64, transposed = false, elementBitWidth = 16}>
#shared_b = #ttg.nvmma_shared<{swizzlingByteWidth = 32, transposed = false, elementBitWidth = 16}>
#smem = #ttg.shared_memory
module attributes {"ttg.target" = "cuda:0", "ttg.num-ctas" = 1 : i32, "ttg.num-warps" = 1 : i32, "ttg.threads-per-warp" = 32 : i32} {
  // CHECK-LABEL: @memdesc_reinterpret_multibuffer_prefix_subview
  tt.func @memdesc_reinterpret_multibuffer_prefix_subview(%arg0: !ttg.memdesc<3x8x32xf16, #shared_a, #smem, 8x8x32>) {
    // CHECK: ttg.memdesc_reinterpret
    %0 = ttg.memdesc_reinterpret %arg0 : !ttg.memdesc<3x8x32xf16, #shared_a, #smem, 8x8x32> -> !ttg.memdesc<6x8x16xf16, #shared_b, #smem>
    tt.return
  }
}

// -----

#shared_cga_01 = #ttg.swizzled_shared<{vec = 1, perPhase = 1, maxPhase = 1, order = [1, 0], CGALayout = [[0, 1]]}>
#shared_cga_10 = #ttg.swizzled_shared<{vec = 1, perPhase = 1, maxPhase = 1, order = [1, 0], CGALayout = [[1, 0]]}>
#shared_cga_00 = #ttg.swizzled_shared<{vec = 1, perPhase = 1, maxPhase = 1, order = [1, 0], CGALayout = [[0, 0]]}>
#shared = #ttg.shared_linear<{offset = [[0, 1], [0, 2], [1, 0], [4, 0]], block = [[2, 0]]}, alignment = 16>
#smem = #ttg.shared_memory
module attributes {"ttg.target" = "cuda:0", "ttg.num-ctas" = 2 : i32, "ttg.num-warps" = 1 : i32, "ttg.threads-per-warp" = 32 : i32} {
  // CHECK-LABEL: @subslice_non_trivial_block_cga_01
  tt.func @subslice_non_trivial_block_cga_01(%arg0: !ttg.memdesc<8x16xf32, #shared_cga_01, #smem>) {
    // CHECK: ttg.memdesc_subslice %{{.*}}[0, 0]
    %0 = ttg.memdesc_subslice %arg0 [0, 0] : !ttg.memdesc<8x16xf32, #shared_cga_01, #smem> -> !ttg.memdesc<4x16xf32, #shared_cga_01, #smem, 8x16>
    tt.return
  }

  // CHECK-LABEL: @subslice_non_trivial_block_cga_10
  tt.func @subslice_non_trivial_block_cga_10(%arg0: !ttg.memdesc<8x16xf32, #shared_cga_10, #smem>) {
    // CHECK: ttg.memdesc_subslice %{{.*}}[0, 0]
    %0 = ttg.memdesc_subslice %arg0 [0, 0] : !ttg.memdesc<8x16xf32, #shared_cga_10, #smem> -> !ttg.memdesc<8x8xf32, #shared_cga_10, #smem, 8x16>
    tt.return
  }

  // CHECK-LABEL: @subslice_broadcasted_block_cga_00
  tt.func @subslice_broadcasted_block_cga_00(%arg0: !ttg.memdesc<8x16xf32, #shared_cga_00, #smem>) {
    // CHECK: ttg.memdesc_subslice %{{.*}}[0, 0]
    %0 = ttg.memdesc_subslice %arg0 [0, 0] : !ttg.memdesc<8x16xf32, #shared_cga_00, #smem> -> !ttg.memdesc<4x16xf32, #shared_cga_00, #smem, 8x16>
    tt.return
  }

  // CHECK-LABEL: @subview_split_on_cta_dim
  tt.func @subview_split_on_cta_dim(%arg0: !ttg.memdesc<8x4xf32, #shared, #smem>) {
    // CHECK: ttg.memdesc_subslice %{{.*}}[0, 0]
    %a = ttg.memdesc_subslice %arg0 [0, 0] : !ttg.memdesc<8x4xf32, #shared, #smem> -> !ttg.memdesc<4x4xf32, #shared, #smem, 8x4>
    tt.return
  }

  // CHECK-LABEL: @memdesc_reinterpret_shared_sharding
  tt.func @memdesc_reinterpret_shared_sharding(%broadcast: !ttg.memdesc<8x16xf16, #shared_cga_00, #smem, mutable>) {
    %split = ttg.memdesc_reinterpret %broadcast : !ttg.memdesc<8x16xf16, #shared_cga_00, #smem, mutable> -> !ttg.memdesc<8x16xi16, #shared_cga_10, #smem, mutable>
    %view = ttg.memdesc_subslice %broadcast [0, 0] : !ttg.memdesc<8x16xf16, #shared_cga_00, #smem, mutable> -> !ttg.memdesc<4x16xf16, #shared_cga_00, #smem, mutable, 8x16>
    %split_view = ttg.memdesc_reinterpret %view : !ttg.memdesc<4x16xf16, #shared_cga_00, #smem, mutable, 8x16> -> !ttg.memdesc<4x16xi16, #shared_cga_10, #smem, mutable>
    tt.return
  }
}

// -----

#shared = #ttg.padded_shared<[4:+4] {offset=[[1, 0], [2, 0], [0, 1], [0, 2]], block=[]}>
#smem = #ttg.shared_memory
module attributes {"ttg.target" = "gfx950", "ttg.num-ctas" = 1 : i32, "ttg.num-warps" = 1 : i32, "ttg.threads-per-warp" = 64 : i32} {
  // CHECK-LABEL: memdesc_padded_same_rank_than_shape
  tt.func @memdesc_padded_same_rank_than_shape(%d : !ttg.memdesc<4x4xf16, #shared, #smem, mutable, 3x4x4>) {
    tt.return
  }

  // CHECK-LABEL: memdesc_padded_with_pipeline_dim
  tt.func @memdesc_padded_with_pipeline_dim(%d : !ttg.memdesc<3x4x4xf32, #shared, #smem, mutable>){
    tt.return
  }
}

// -----

#shared = #ttg.nvmma_shared<{swizzlingByteWidth = 64, transposed = false, elementBitWidth = 16, rank = 4}>
#shared1 = #ttg.nvmma_shared<{swizzlingByteWidth = 64, transposed = false, elementBitWidth = 16}>
#shared2 = #ttg.nvmma_shared<{swizzlingByteWidth = 64, transposed = true, elementBitWidth = 32}>
#shared_linear_16 = #ttg.shared_linear<{offset = [[0, 1], [0, 2], [0, 4], [0, 8], [1, 0], [2, 4], [4, 8], [8, 0]]}, alignment = 512>
#shared_linear_equiv = #ttg.shared_linear<{offset = [[0, 0, 1, 0], [0, 1, 0, 0], [0, 2, 0, 0], [0, 4, 0, 0], [0, 0, 0, 1], [0, 2, 0, 2], [0, 4, 0, 4], [0, 0, 0, 8]]}, alignment = 512>
#smem = #ttg.shared_memory
module attributes {"ttg.target" = "cuda:0", "ttg.num-ctas" = 1 : i32, "ttg.num-warps" = 1 : i32, "ttg.threads-per-warp" = 32 : i32} {
  // CHECK-LABEL: memdesc_reshape
  // CHECK: !ttg.memdesc<128x64xf16, #{{.+}}, mutable>
  tt.func @memdesc_reshape(%d : !ttg.memdesc<32x1x4x64xf16, #shared, #smem, mutable>){
    %1 = ttg.memdesc_reshape %d : !ttg.memdesc<32x1x4x64xf16, #shared, #smem, mutable> -> !ttg.memdesc<128x64xf16, #shared1, #smem, mutable>
    tt.return
  }

  // CHECK-LABEL: memdesc_reshape_equiv
  // CHECK: %[[R:.*]] = ttg.memdesc_reshape %{{.*}} : !ttg.memdesc<1x8x2x16xf32, #{{.*}}, #smem> -> !ttg.memdesc<16x16xf32, #{{.*}}, #smem>
  tt.func @memdesc_reshape_equiv(%arg0 : !ttg.memdesc<1x8x2x16xf32, #shared_linear_equiv, #smem>) {
    %0 = ttg.memdesc_reshape %arg0 : !ttg.memdesc<1x8x2x16xf32, #shared_linear_equiv, #smem> -> !ttg.memdesc<16x16xf32, #shared2, #smem>
    tt.return
  }

  // CHECK-LABEL: memdesc_trans_equiv
  // CHECK: %[[T:.*]] = ttg.memdesc_trans %{{.*}} {order = array<i32: 1, 0>} : !ttg.memdesc<16x16xf32, #{{.*}}, #smem> -> !ttg.memdesc<16x16xf32, #{{.*}}, #smem>
  tt.func @memdesc_trans_equiv(%arg0 : !ttg.memdesc<16x16xf32, #shared_linear_16, #smem>) {
    %0 = ttg.memdesc_trans %arg0 {order = array<i32: 1, 0>} : !ttg.memdesc<16x16xf32, #shared_linear_16, #smem> -> !ttg.memdesc<16x16xf32, #shared2, #smem>
    tt.return
  }
}

// -----

#src = #ttg.generic_linear<{register = [[1, 0], [0, 1]], lane = [[2, 0], [4, 0], [8, 0], [0, 2], [0, 4]], warp = [[16, 8], [0, 8]], block = []}>
#dst = #ttg.generic_linear<{register = [[1]], lane = [[2], [4], [8], [0], [0]], warp = [[16], [0]], block = []}>

module attributes {"ttg.num-ctas" = 1 : i32, "ttg.num-warps" = 4 : i32, "ttg.threads-per-warp" = 32 : i32} {
  // CHECK-LABEL: @reshape_generic_linear_to_permutation
  // CHECK: tt.reshape
  tt.func @reshape_generic_linear_to_permutation(%arg: tensor<32x1xi32, #src>) {
    %0 = tt.reshape %arg : tensor<32x1xi32, #src> -> tensor<32xi32, #dst>
    tt.return
  }
}

// -----

#shared1d = #ttg.swizzled_shared<{vec = 1, perPhase = 1, maxPhase = 1, order = [0]}>
#shared2d = #ttg.swizzled_shared<{vec = 1, perPhase = 1, maxPhase = 1, order = [1, 0]}>
#smem = #ttg.shared_memory
module attributes {"ttg.target" = "cuda:0", "ttg.num-ctas" = 1 : i32, "ttg.num-warps" = 1 : i32, "ttg.threads-per-warp" = 32 : i32} {
  // CHECK-LABEL: memdesc_reinterpret_layout_rank_increase
  // CHECK: ttg.memdesc_reinterpret
  tt.func @memdesc_reinterpret_layout_rank_increase(%arg0 : !ttg.memdesc<32x2xi32, #shared1d, #smem, mutable>) {
    %0 = ttg.memdesc_reinterpret %arg0 : !ttg.memdesc<32x2xi32, #shared1d, #smem, mutable> -> !ttg.memdesc<32x2xi32, #shared2d, #smem, mutable>
    tt.return
  }

  // CHECK-LABEL: memdesc_reinterpret_layout_rank_decrease
  // CHECK: ttg.memdesc_reinterpret
  tt.func @memdesc_reinterpret_layout_rank_decrease(%arg0 : !ttg.memdesc<32x2xi32, #shared2d, #smem, mutable>) {
    %0 = ttg.memdesc_reinterpret %arg0 : !ttg.memdesc<32x2xi32, #shared2d, #smem, mutable> -> !ttg.memdesc<32x2xi32, #shared1d, #smem, mutable>
    tt.return
  }

  // CHECK-LABEL: memdesc_reinterpret_smaller_smem
  // CHECK: ttg.memdesc_reinterpret
  tt.func @memdesc_reinterpret_smaller_smem(%arg0 : !ttg.memdesc<32x2xi32, #shared2d, #smem, mutable>) {
    %0 = ttg.memdesc_reinterpret %arg0 : !ttg.memdesc<32x2xi32, #shared2d, #smem, mutable> -> !ttg.memdesc<32x2xi16, #shared2d, #smem, mutable>
    tt.return
  }
}

// -----

#tmem = #ttng.tensor_memory_encoding<blockM = 128, blockN = 128, colStride = 1>
module attributes {"ttg.num-ctas" = 1 : i32, "ttg.num-warps" = 4 : i32} {
  // CHECK-LABEL: memdesc_reinterpret_smaller_tmem
  // CHECK: ttg.memdesc_reinterpret
  tt.func @memdesc_reinterpret_smaller_tmem(%arg0: !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory>) {
    %0 = ttg.memdesc_reinterpret %arg0 : !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory> -> !ttg.memdesc<128x128xf16, #tmem, #ttng.tensor_memory>
    tt.return
  }
}

// -----

#shared = #ttg.swizzled_shared<{vec = 1, perPhase = 1, maxPhase = 1, order = [1, 0]}>
#shared_dense = #ttg.shared_linear<{offset = [[0, 1], [0, 2], [1, 0], [2, 0]], block = []}, alignment = 16>
#shared_holey = #ttg.shared_linear<{offset = [[0, 1], [0, 0], [1, 0], [2, 0]], block = []}, alignment = 16>
#shared_holey_view = #ttg.shared_linear<{offset = [[0, 1], [0, 2], [1, 0]], block = []}, alignment = 16>
#shared_padded = #ttg.padded_shared<[128:+8] {order = [1, 0], shape = [16, 128]}>
#smem = #ttg.shared_memory
module attributes {"ttg.target" = "cuda:90", "ttg.num-ctas" = 1 : i32, "ttg.num-warps" = 4 : i32, "ttg.threads-per-warp" = 32 : i32} {
  // CHECK-LABEL: @memdesc_subslice_pipeline_stage_chain
  // CHECK: ttg.memdesc_subslice {{.*}}[3, 0, 0]
  // CHECK: ttg.memdesc_index
  // CHECK: ttg.memdesc_reinterpret
  tt.func @memdesc_subslice_pipeline_stage_chain(%arg0: !ttg.memdesc<7x16x16xf16, #shared, #smem, mutable>, %index: i32) {
    %stages = ttg.memdesc_subslice %arg0 [3, 0, 0] : !ttg.memdesc<7x16x16xf16, #shared, #smem, mutable> -> !ttg.memdesc<2x16x16xf16, #shared, #smem, mutable, 7x16x16>
    %indexed = ttg.memdesc_index %stages[%index] : !ttg.memdesc<2x16x16xf16, #shared, #smem, mutable, 7x16x16> -> !ttg.memdesc<16x16xf16, #shared, #smem, mutable>
    %reinterpret = ttg.memdesc_reinterpret %stages : !ttg.memdesc<2x16x16xf16, #shared, #smem, mutable, 7x16x16> -> !ttg.memdesc<2x16x16xi16, #shared, #smem, mutable>
    %last = ttg.memdesc_subslice %stages [1, 0, 0] : !ttg.memdesc<2x16x16xf16, #shared, #smem, mutable, 7x16x16> -> !ttg.memdesc<1x16x16xf16, #shared, #smem, mutable, 7x16x16>
    tt.return
  }

  // CHECK-LABEL: @memdesc_reinterpret_pipeline_subview_with_gaps
  tt.func @memdesc_reinterpret_pipeline_subview_with_gaps(%arg0: !ttg.memdesc<7x16x16xf16, #shared, #smem, mutable>) {
    %view = ttg.memdesc_subslice %arg0 [3, 8, 0] : !ttg.memdesc<7x16x16xf16, #shared, #smem, mutable> -> !ttg.memdesc<2x8x16xf16, #shared, #smem, mutable, 7x16x16>
    %result = ttg.memdesc_reinterpret %view : !ttg.memdesc<2x8x16xf16, #shared, #smem, mutable, 7x16x16> -> !ttg.memdesc<8x16xi16, #shared, #smem, mutable>
    %stages = ttg.memdesc_reinterpret %view : !ttg.memdesc<2x8x16xf16, #shared, #smem, mutable, 7x16x16> -> !ttg.memdesc<2x4x16xi16, #shared, #smem, mutable>
    tt.return
  }

  // CHECK-LABEL: @memdesc_reinterpret_noncontiguous_shared_subview_prefix
  tt.func @memdesc_reinterpret_noncontiguous_shared_subview_prefix(%arg0: !ttg.memdesc<4x4xi32, #shared_dense, #smem, mutable>) {
    %view = ttg.memdesc_subslice %arg0 [0, 0] : !ttg.memdesc<4x4xi32, #shared_dense, #smem, mutable> -> !ttg.memdesc<4x2xi32, #shared_dense, #smem, mutable, 4x4>
    %result = ttg.memdesc_reinterpret %view : !ttg.memdesc<4x2xi32, #shared_dense, #smem, mutable, 4x4> -> !ttg.memdesc<1x2xi32, #shared, #smem, mutable>
    tt.return
  }

  // CHECK-LABEL: @memdesc_reinterpret_subview_owns_zero_bases
  tt.func @memdesc_reinterpret_subview_owns_zero_bases(%arg0: !ttg.memdesc<2x2xi32, #shared_holey, #smem, mutable, 4x2>) {
    %result = ttg.memdesc_reinterpret %arg0 : !ttg.memdesc<2x2xi32, #shared_holey, #smem, mutable, 4x2> -> !ttg.memdesc<2x4xi32, #shared_holey_view, #smem, mutable>
    tt.return
  }

  // CHECK-LABEL: @memdesc_reinterpret_full_allocation_with_zero_bases
  tt.func @memdesc_reinterpret_full_allocation_with_zero_bases(%arg0: !ttg.memdesc<4x2xi32, #shared_holey, #smem, mutable>) {
    %result = ttg.memdesc_reinterpret %arg0 : !ttg.memdesc<4x2xi32, #shared_holey, #smem, mutable> -> !ttg.memdesc<4x4xi32, #shared_dense, #smem, mutable>
    tt.return
  }

  // CHECK-LABEL: @memdesc_reinterpret_full_padded
  tt.func @memdesc_reinterpret_full_padded(%arg0: !ttg.memdesc<16x128xf16, #shared_padded, #smem, mutable>) {
    %result = ttg.memdesc_reinterpret %arg0 : !ttg.memdesc<16x128xf16, #shared_padded, #smem, mutable> -> !ttg.memdesc<16x128xbf16, #shared_padded, #smem, mutable>
    tt.return
  }
}

// -----

#tmem = #ttng.tensor_memory_encoding<blockM = 128, blockN = 64, colStride = 1>
module attributes {"ttg.num-ctas" = 1 : i32, "ttg.num-warps" = 4 : i32} {
  // CHECK-LABEL: @tmem_reinterpret_noncontiguous_subview_prefix
  tt.func @tmem_reinterpret_noncontiguous_subview_prefix(%arg0: !ttg.memdesc<256x256xf32, #tmem, #ttng.tensor_memory, mutable>) {
    %view = ttng.tmem_subslice %arg0 {offset = 128 : i32, dim = 0 : i32} : !ttg.memdesc<256x256xf32, #tmem, #ttng.tensor_memory, mutable> -> !ttg.memdesc<128x256xf32, #tmem, #ttng.tensor_memory, mutable, 256x256>
    %result = ttg.memdesc_reinterpret %view : !ttg.memdesc<128x256xf32, #tmem, #ttng.tensor_memory, mutable, 256x256> -> !ttg.memdesc<128x64xf32, #tmem, #ttng.tensor_memory, mutable>
    tt.return
  }

  // CHECK-LABEL: @tmem_reinterpret_packed_subview_owns_column
  tt.func @tmem_reinterpret_packed_subview_owns_column(%arg0: !ttg.memdesc<128x4xi8, #tmem, #ttng.tensor_memory, mutable>) {
    %view = ttng.tmem_subslice %arg0 {offset = 0 : i32} : !ttg.memdesc<128x4xi8, #tmem, #ttng.tensor_memory, mutable> -> !ttg.memdesc<128x2xi8, #tmem, #ttng.tensor_memory, mutable, 128x4>
    %result = ttg.memdesc_reinterpret %view : !ttg.memdesc<128x2xi8, #tmem, #ttng.tensor_memory, mutable, 128x4> -> !ttg.memdesc<128x4xi8, #tmem, #ttng.tensor_memory, mutable>
    tt.return
  }

  // CHECK-LABEL: @tmem_subslice_pipeline_stage_chain
  tt.func @tmem_subslice_pipeline_stage_chain(%arg0: !ttg.memdesc<5x128x128xf32, #tmem, #ttng.tensor_memory, mutable>, %index: i32) {
    %stages = ttng.tmem_subslice %arg0 {offset = 2 : i32, dim = 0 : i32} : !ttg.memdesc<5x128x128xf32, #tmem, #ttng.tensor_memory, mutable> -> !ttg.memdesc<2x128x128xf32, #tmem, #ttng.tensor_memory, mutable, 5x128x128>
    %indexed = ttg.memdesc_index %stages[%index] : !ttg.memdesc<2x128x128xf32, #tmem, #ttng.tensor_memory, mutable, 5x128x128> -> !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable>
    %result = ttg.memdesc_reinterpret %stages : !ttg.memdesc<2x128x128xf32, #tmem, #ttng.tensor_memory, mutable, 5x128x128> -> !ttg.memdesc<2x128x128xf32, #tmem, #ttng.tensor_memory, mutable>
    %last = ttng.tmem_subslice %stages {offset = 1 : i32, dim = 0 : i32} : !ttg.memdesc<2x128x128xf32, #tmem, #ttng.tensor_memory, mutable, 5x128x128> -> !ttg.memdesc<1x128x128xf32, #tmem, #ttng.tensor_memory, mutable, 5x128x128>
    tt.return
  }
}

// -----

// CHECK: #ttg.nvmma_shared<{swizzlingByteWidth = 64, transposed = false, elementBitWidth = 16, CGALayout = {{\[\[1, 0, 0, 0, 0\]\]}}}>
#shared_rank_5 = #ttg.nvmma_shared<{swizzlingByteWidth = 64, transposed = false, elementBitWidth = 16, CGALayout = [[1, 0, 0, 0, 0]]}>
#smem = #ttg.shared_memory
module attributes {"ttg.target" = "cuda:0", "ttg.num-ctas" = 1 : i32, "ttg.num-warps" = 1 : i32, "ttg.threads-per-warp" = 32 : i32} {
  tt.func @nvmma_rank_inference(%arg0 : !ttg.memdesc<1x1x1x1x32xf16, #shared_rank_5, #smem>) {
    tt.return
  }
}


// -----

// CHECK-LABEL: @warp_specialize_nothing
tt.func @warp_specialize_nothing() {
  // CHECK-NEXT: ttg.warp_specialize()
  ttg.warp_specialize()
  // CHECK-NEXT: default {
  default {
    // CHECK-NEXT: ttg.warp_yield
    ttg.warp_yield
  // CHECK-NEXT: } : () -> ()
  } : () -> ()
  tt.return
}

// CHECK-LABEL: @warp_specialize_no_partitions
tt.func @warp_specialize_no_partitions(%arg0: i32, %arg1: i64) -> i64 {
  // CHECK-NEXT: %0 = ttg.warp_specialize(%arg0)
  %0 = ttg.warp_specialize(%arg0)
  // CHECK-NEXT: default {
  default {
    // CHECK-NEXT: ttg.warp_yield %arg1 : i64
    ttg.warp_yield %arg1 : i64
  // CHECK-NEXT: } : (i32) -> i64
  } : (i32) -> i64
  tt.return %0 : i64
}

// CHECK-LABEL: @warp_specialize_partitions
tt.func @warp_specialize_partitions(%arg0: i32, %arg1: i64) -> i64 {
  // CHECK-NEXT: %0 = ttg.warp_specialize(%arg0)
  %0 = ttg.warp_specialize(%arg0)
  // CHECK-NEXT: default {
  default {
    // CHECK-NEXT: ttg.warp_yield %arg1 : i64
    ttg.warp_yield %arg1 : i64
  // CHECK-NEXT: }
  }
  // CHECK-NEXT: partition0(%arg2: i32) num_warps(4) {
  partition0(%arg2: i32) num_warps(4) {
    // CHECK-NEXT: arith.addi %arg2, %arg2 : i32
    %1 = arith.addi %arg2, %arg2 : i32
    // CHECK-NEXT: ttg.warp_return
    ttg.warp_return
  // CHECK-NEXT: }
  }
  // CHECK-NEXT: partition1(%arg2: i32) num_warps(1) {
  partition1(%arg2: i32) num_warps(1) {
    // CHECK-NEXT: ttg.warp_return
    ttg.warp_return
  // CHECK-NEXT: }
  }
  // CHECK-NEXT: partition2(%arg2: i32) num_warps(8) {
  partition2(%arg2: i32) num_warps(8) {
    // CHECK-NEXT: arith.muli
    %1 = arith.muli %arg2, %arg2 : i32
    // CHECK-NEXT: ttg.warp_return
    ttg.warp_return
  // CHECK-NEXT: } : (i32) -> i64
  } : (i32) -> i64
  tt.return %0 : i64
}

// CHECK-LABEL: @warp_specialize_multiple_args
tt.func @warp_specialize_multiple_args_res(%arg0: i32, %arg1: i32) -> (i32, i32) {
  // CHECK-NEXT: %0:2 = ttg.warp_specialize(%arg0, %arg1)
  %0:2 = ttg.warp_specialize(%arg0, %arg1)
  // CHECK-NEXT: default {
  default {
    // CHECK-NEXT: ttg.warp_yield %arg0, %arg1 : i32, i32
    ttg.warp_yield %arg0, %arg1 : i32, i32
  // CHECK-NEXT: }
  }
  // CHECK-NEXT: partition0(%arg2: i32, %arg3: i32) num_warps(4) {
  partition0(%arg2: i32, %arg3: i32) num_warps(4) {
    // CHECK-NEXT: arith.addi %arg2, %arg3 : i32
    %1 = arith.addi %arg2, %arg3 : i32
    // CHECK-NEXT: ttg.warp_return
    ttg.warp_return
  // CHECK-NEXT: } : (i32, i32) -> (i32, i32)
  } : (i32, i32) -> (i32, i32)
  tt.return %0#0, %0#1 : i32, i32
}

// -----

// CHECK-DAG: [[BLOCKED_1_WARPS:#.*]] = #ttg.blocked{{.*}} warpsPerCTA = [1]
#blocked_1_warps = #ttg.blocked<{sizePerThread = [1], threadsPerWarp = [32], warpsPerCTA = [1], order = [0]}>
// CHECK-DAG: [[BLOCKED_2_WARPS:#.*]] = #ttg.blocked{{.*}} warpsPerCTA = [2]
#blocked_2_warps = #ttg.blocked<{sizePerThread = [1], threadsPerWarp = [32], warpsPerCTA = [2], order = [0]}>
// CHECK-DAG: [[BLOCKED_4_WARPS:#.*]] = #ttg.blocked{{.*}} warpsPerCTA = [4]
#blocked_4_warps = #ttg.blocked<{sizePerThread = [1], threadsPerWarp = [32], warpsPerCTA = [4], order = [0]}>
// CHECK-DAG: [[BLOCKED_8_WARPS:#.*]] = #ttg.blocked{{.*}} warpsPerCTA = [8]
#blocked_8_warps = #ttg.blocked<{sizePerThread = [1], threadsPerWarp = [32], warpsPerCTA = [8], order = [0]}>

module attributes {"ttg.num-warps" = 4 : i32} {

// CHECK: @function_scope
tt.func @function_scope() attributes {"ttg.num-warps" = 8 : i32} {
  // CHECK-NEXT: tt.make_range {{.*}} tensor<128xi32, [[BLOCKED_8_WARPS]]>
  tt.make_range {end = 128 : i32, start = 0 : i32} : tensor<128xi32, #blocked_8_warps>
  tt.return
}

// CHECK: @function_no_scope
tt.func @function_no_scope() {
  // CHECK-NEXT: tt.make_range {{.*}} tensor<128xi32, [[BLOCKED_4_WARPS]]>
  tt.make_range {end = 128 : i32, start = 0 : i32} : tensor<128xi32, #blocked_4_warps>
  // CHECK-NEXT: ttg.warp_specialize()
  ttg.warp_specialize()
  default {
    ttg.warp_yield
  }
  // CHECK: partition0() num_warps(2)
  partition0() num_warps(2) {
    // CHECK-NEXT: tt.make_range {{.*}} tensor<128xi32, [[BLOCKED_2_WARPS]]>
    tt.make_range {end = 128 : i32, start = 0 : i32} : tensor<128xi32, #blocked_2_warps>
    ttg.warp_return
  }
  // CHECK: partition1() num_warps(1)
  partition1() num_warps(1) {
    // CHECK-NEXT: tt.make_range {{.*}} tensor<128xi32, [[BLOCKED_1_WARPS]]>
    tt.make_range {end = 128 : i32, start = 0 : i32} : tensor<128xi32, #blocked_1_warps>
    ttg.warp_return
  } : () -> ()
  tt.return
}

}

// -----

// CHECK-DAG: [[$BLOCKED:#.*]] = #ttg.blocked
#blocked = #ttg.blocked<{sizePerThread = [1, 8], threadsPerWarp = [4, 8], warpsPerCTA = [4, 1], order = [1, 0]}>
// CHECK-DAG: [[$LINEAR:#.*]] = #ttg.linear
#linear = #ttg.linear<{register = [[0, 1], [16, 0], [32, 0], [64, 0]], lane = [[0, 0], [0, 0], [0, 0], [1, 0], [2, 0]], warp = [[4, 0], [8, 0]], block = []}>

module attributes {"ttg.num-warps" = 4 : i32} {
// CHECK-LABEL: @split_join_linear_mix
tt.func @split_join_linear_mix(%arg: tensor<128x2xf32, #linear>) attributes {"ttg.num-warps" = 4 : i32} {
  // CHECK-NEXT: tt.split %{{.*}} : tensor<128x2xf32, [[$LINEAR]]> -> tensor<128xf32, #ttg.slice<{dim = 1, parent = [[$BLOCKED]]}>>
  %lhs, %rhs = tt.split %arg : tensor<128x2xf32, #linear> -> tensor<128xf32, #ttg.slice<{dim = 1, parent = #blocked}>>
  // CHECK-NEXT: tt.join %{{.*}}, %{{.*}} : tensor<128xf32, #ttg.slice<{dim = 1, parent = [[$BLOCKED]]}>> -> tensor<128x2xf32, [[$LINEAR]]>
  %j = tt.join %lhs, %rhs : tensor<128xf32, #ttg.slice<{dim = 1, parent = #blocked}>> -> tensor<128x2xf32, #linear>
  tt.return
}
}

// -----

// CHECK-LABEL: @async_commit_group
tt.func @async_commit_group(%arg0: !ttg.async.token) {
  // CHECK-NEXT: ttg.async_commit_group
  ttg.async_commit_group
  // CHECK-NEXT: ttg.async_commit_group tokens %arg0
  %0 = ttg.async_commit_group tokens %arg0
  // CHECK-NEXT: ttg.async_commit_group
  %1 = ttg.async_commit_group
  tt.return
}

// -----

#blocked = #ttg.blocked<{sizePerThread = [1, 1], threadsPerWarp = [2, 2], warpsPerCTA = [1, 1], order = [1, 0]}>
#shared = #ttg.shared_linear<{offset = [[0, 1], [0, 2], [1, 0], [2, 2]]}, alignment = 16>
#smem = #ttg.shared_memory

module attributes {"ttg.threads-per-warp" = 4 : i32, "ttg.num-warps" = 1 : i32} {
  tt.func @round_trip(%arg0: tensor<4x4xf32, #blocked>) -> tensor<4x4xf32, #blocked> {
    // CHECK: ttg.local_alloc
    // CHECK-SAME: !ttg.memdesc<4x4xf32, #shared
    %alloc = ttg.local_alloc %arg0 : (tensor<4x4xf32, #blocked>) -> !ttg.memdesc<4x4xf32, #shared, #smem, mutable>
    ttg.local_store %arg0, %alloc : tensor<4x4xf32, #blocked> -> !ttg.memdesc<4x4xf32, #shared, #smem, mutable>
    %loaded = ttg.local_load %alloc : !ttg.memdesc<4x4xf32, #shared, #smem, mutable> -> tensor<4x4xf32, #blocked>
    tt.return %loaded : tensor<4x4xf32, #blocked>
  }
}

// -----

#mma_assert = #ttg.amd_wmma<{version = 3, isTranspose = true, ctaLayout = {register = [[0, 1], [2, 0]], warp = [[2, 2], [1, 0]]}, instrShape = [16, 16, 32]}>

module attributes {"ttg.target" = "hip:gfx1260", "ttg.num-ctas" = 1 : i32, "ttg.num-warps" = 4 : i32, "ttg.threads-per-warp" = 32 : i32} {
  // CHECK-LABEL: @assert_generic_wmma_slice_layout
  tt.func @assert_generic_wmma_slice_layout(%cond: tensor<64xi1, #ttg.slice<{dim = 1, parent = #mma_assert}>>) {
    // CHECK: tt.assert
    tt.assert %cond, "assert generic wmma slice layout" : tensor<64xi1, #ttg.slice<{dim = 1, parent = #mma_assert}>>
    tt.return
  }
}

// -----

#one_hot_basis = #ttg.blocked<{sizePerThread = [1], threadsPerWarp = [32], warpsPerCTA = [4], order = [0]}>
#one_hot_index = #ttg.blocked<{sizePerThread = [2], threadsPerWarp = [32], warpsPerCTA = [4], order = [0]}>
#one_hot_multiple_registers = #ttg.blocked<{sizePerThread = [4], threadsPerWarp = [32], warpsPerCTA = [4], order = [0]}>
#one_hot_cross_warp_parent = #ttg.blocked<{sizePerThread = [1, 1], threadsPerWarp = [4, 8], warpsPerCTA = [1, 4], order = [1, 0]}>
#one_hot_cross_warp = #ttg.slice<{dim = 0, parent = #one_hot_cross_warp_parent}>
#one_hot_permuted = #ttg.linear<{register = [], lane = [[2], [1], [4], [8], [16]], warp = [[0], [0]], block = []}>

module attributes {"ttg.target" = "cuda:90", "ttg.num-ctas" = 1 : i32, "ttg.num-warps" = 4 : i32, "ttg.threads-per-warp" = 32 : i32} {
  // The reduction is useful on its own: recognizing it must not require a
  // primitive, an accumulation chain, or any particular basis producer.
  // CHECK-LABEL: @one_hot_xor_independent_reduction
  // ONE-HOT-LABEL: @one_hot_xor_independent_reduction
  // ONE-HOT: [[COMPUTED:%.*]] = arith.xori
  // ONE-HOT-NOT: "tt.reduce"
  // ONE-HOT: [[GATHERED:%.*]] = tt.gather [[COMPUTED]]
  // ONE-HOT: [[SCALAR:%.*]] = tt.unsplat [[GATHERED]]
  // ONE-HOT: tt.return [[SCALAR]]
  tt.func @one_hot_xor_independent_reduction(%bases: tensor<32xi32, #one_hot_basis>) -> i32 {
    %offsets = tt.make_range {start = 0 : i32, end = 32 : i32} : tensor<32xi32, #one_hot_basis>
    %computed = arith.xori %bases, %offsets : tensor<32xi32, #one_hot_basis>
    %bit = arith.constant dense<7> : tensor<32xi32, #one_hot_basis>
    %zero = arith.constant dense<0> : tensor<32xi32, #one_hot_basis>
    %condition = arith.cmpi eq, %offsets, %bit : tensor<32xi32, #one_hot_basis>
    %selected = arith.select %condition, %computed, %zero : tensor<32xi1, #one_hot_basis>, tensor<32xi32, #one_hot_basis>
    %reduced = "tt.reduce"(%selected) <{axis = 0 : i32}> ({
      ^bb0(%left: i32, %right: i32):
        %combined = arith.xori %left, %right : i32
        tt.reduce.return %combined : i32
    }) : (tensor<32xi32, #one_hot_basis>) -> i32
    tt.return %reduced : i32
  }

  // Lane permutations and commuted equality comparisons still identify one
  // basis value owned by the current warp.
  // CHECK-LABEL: @one_hot_xor_permuted_commuted
  // ONE-HOT-LABEL: @one_hot_xor_permuted_commuted
  // ONE-HOT-NOT: "tt.reduce"
  // ONE-HOT: tt.gather
  // ONE-HOT: tt.unsplat
  // ONE-HOT: tt.return
  tt.func @one_hot_xor_permuted_commuted(%bases: tensor<32xi32, #one_hot_permuted>) -> i32 {
    %offsets = tt.make_range {start = 0 : i32, end = 32 : i32} : tensor<32xi32, #one_hot_permuted>
    %bit = arith.constant dense<11> : tensor<32xi32, #one_hot_permuted>
    %zero = arith.constant dense<0> : tensor<32xi32, #one_hot_permuted>
    %condition = arith.cmpi eq, %bit, %offsets : tensor<32xi32, #one_hot_permuted>
    %selected = arith.select %condition, %bases, %zero : tensor<32xi1, #one_hot_permuted>, tensor<32xi32, #one_hot_permuted>
    %reduced = "tt.reduce"(%selected) <{axis = 0 : i32}> ({
      ^bb0(%left: i32, %right: i32):
        %combined = arith.xori %left, %right : i32
        tt.reduce.return %combined : i32
    }) : (tensor<32xi32, #one_hot_permuted>) -> i32
    tt.return %reduced : i32
  }

  // The ordinary user-written conditional XOR also combines into NVIDIA LOP3
  // after its independent one-hot reduction has become a warp gather.
  // CHECK-LABEL: @one_hot_xor_conditional_accumulation
  // ONE-HOT-LABEL: @one_hot_xor_conditional_accumulation
  // ONE-HOT-NOT: "tt.reduce"
  // ONE-HOT: tt.gather
  // ONE-HOT: [[SCALAR:%.*]] = tt.unsplat
  // ONE-HOT: [[FROZEN:%.*]] = llvm.freeze [[SCALAR]] : i32
  // ONE-HOT: [[BROADCAST:%.*]] = tt.splat [[FROZEN]]
  // ONE-HOT: tt.elementwise_inline_asm "lop3.b32 $0, $1, $2, $3, 0x78;" {{.*}}, [[BROADCAST]],
  // ONE-HOT: tt.return
  tt.func @one_hot_xor_conditional_accumulation(%index: tensor<128xi32, #one_hot_index>, %bases: tensor<32xi32, #one_hot_basis>) -> tensor<128xi32, #one_hot_index> {
    %offsets = tt.make_range {start = 0 : i32, end = 32 : i32} : tensor<32xi32, #one_hot_basis>
    %bit = arith.constant 5 : i32
    %basis_bit = tt.splat %bit : i32 -> tensor<32xi32, #one_hot_basis>
    %zero_basis = arith.constant dense<0> : tensor<32xi32, #one_hot_basis>
    %zero_index = arith.constant dense<0> : tensor<128xi32, #one_hot_index>
    %is_basis_bit = arith.cmpi eq, %offsets, %basis_bit : tensor<32xi32, #one_hot_basis>
    %selected = arith.select %is_basis_bit, %bases, %zero_basis : tensor<32xi1, #one_hot_basis>, tensor<32xi32, #one_hot_basis>
    %reduced = "tt.reduce"(%selected) <{axis = 0 : i32}> ({
      ^bb0(%left: i32, %right: i32):
        %combined = arith.xori %left, %right : i32
        tt.reduce.return %combined : i32
    }) : (tensor<32xi32, #one_hot_basis>) -> i32
    %broadcast = tt.splat %reduced : i32 -> tensor<128xi32, #one_hot_index>
    %condition = arith.cmpi ne, %index, %zero_index : tensor<128xi32, #one_hot_index>
    %contribution = arith.select %condition, %broadcast, %zero_index : tensor<128xi1, #one_hot_index>, tensor<128xi32, #one_hot_index>
    %result = arith.xori %index, %contribution : tensor<128xi32, #one_hot_index>
    tt.return %result : tensor<128xi32, #one_hot_index>
  }

  // The original select may mask a poison reduction result. Only the basis
  // consumed by the eager LOP3 is frozen; other masked scalar and tensor uses
  // must keep consuming the original value.
  // CHECK-LABEL: @one_hot_xor_poison_masking
  // ONE-HOT-LABEL: @one_hot_xor_poison_masking
  // ONE-HOT: [[POISON:%.*]] = ub.poison
  // ONE-HOT-NOT: "tt.reduce"
  // ONE-HOT: [[GATHERED:%.*]] = tt.gather [[POISON]]
  // ONE-HOT: [[SCALAR:%.*]] = tt.unsplat [[GATHERED]]
  // ONE-HOT: [[ORIGINAL:%.*]] = tt.splat [[SCALAR]]
  // ONE-HOT: [[FROZEN:%.*]] = llvm.freeze [[SCALAR]] : i32
  // ONE-HOT: [[BROADCAST:%.*]] = tt.splat [[FROZEN]]
  // ONE-HOT: [[FUSED:%.*]] = tt.elementwise_inline_asm "lop3.b32 $0, $1, $2, $3, 0x78;" {{.*}}, [[BROADCAST]],
  // ONE-HOT: [[MASKED_TENSOR:%.*]] = arith.select {{.*}}, [[ORIGINAL]],
  // ONE-HOT: [[MASKED_SCALAR:%.*]] = arith.select {{.*}}, [[SCALAR]],
  // ONE-HOT: tt.return [[FUSED]], [[MASKED_TENSOR]], [[MASKED_SCALAR]]
  tt.func @one_hot_xor_poison_masking(%index: tensor<128xi32, #one_hot_index>, %condition: tensor<128xi1, #one_hot_index>, %other_condition: tensor<128xi1, #one_hot_index>, %scalar_condition: i1) -> (tensor<128xi32, #one_hot_index>, tensor<128xi32, #one_hot_index>, i32) {
    %poison = ub.poison : tensor<32xi32, #one_hot_basis>
    %offsets = tt.make_range {start = 0 : i32, end = 32 : i32} : tensor<32xi32, #one_hot_basis>
    %bit = arith.constant dense<7> : tensor<32xi32, #one_hot_basis>
    %zero_basis = arith.constant dense<0> : tensor<32xi32, #one_hot_basis>
    %zero_index = arith.constant dense<0> : tensor<128xi32, #one_hot_index>
    %zero_scalar = arith.constant 0 : i32
    %is_basis_bit = arith.cmpi eq, %offsets, %bit : tensor<32xi32, #one_hot_basis>
    %selected = arith.select %is_basis_bit, %poison, %zero_basis : tensor<32xi1, #one_hot_basis>, tensor<32xi32, #one_hot_basis>
    %reduced = "tt.reduce"(%selected) <{axis = 0 : i32}> ({
      ^bb0(%left: i32, %right: i32):
        %combined = arith.xori %left, %right : i32
        tt.reduce.return %combined : i32
    }) : (tensor<32xi32, #one_hot_basis>) -> i32
    %broadcast = tt.splat %reduced : i32 -> tensor<128xi32, #one_hot_index>
    %contribution = arith.select %condition, %broadcast, %zero_index : tensor<128xi1, #one_hot_index>, tensor<128xi32, #one_hot_index>
    %result = arith.xori %index, %contribution : tensor<128xi32, #one_hot_index>
    %masked_tensor = arith.select %other_condition, %broadcast, %zero_index : tensor<128xi1, #one_hot_index>, tensor<128xi32, #one_hot_index>
    %masked_scalar = arith.select %scalar_condition, %reduced, %zero_scalar : i32
    tt.return %result, %masked_tensor, %masked_scalar : tensor<128xi32, #one_hot_index>, tensor<128xi32, #one_hot_index>, i32
  }

  // An existing gather is unrelated to a one-hot reduction, even when the same
  // module also contains reductions that this pass can optimize.
  // CHECK-LABEL: @one_hot_xor_existing_gather_unchanged
  // ONE-HOT-LABEL: @one_hot_xor_existing_gather_unchanged
  // ONE-HOT: [[GATHERED:%.*]] = tt.gather
  // ONE-HOT: [[SCALAR:%.*]] = tt.unsplat [[GATHERED]]
  // ONE-HOT: [[BROADCAST:%.*]] = tt.splat [[SCALAR]]
  // ONE-HOT: [[CONTRIBUTION:%.*]] = arith.select {{.*}}, [[BROADCAST]]
  // ONE-HOT-NOT: tt.elementwise_inline_asm
  // ONE-HOT: arith.xori {{.*}}, [[CONTRIBUTION]]
  // ONE-HOT: tt.return
  tt.func @one_hot_xor_existing_gather_unchanged(%index: tensor<128xi32, #one_hot_index>, %bases: tensor<32xi32, #one_hot_basis>) -> tensor<128xi32, #one_hot_index> {
    %bit = arith.constant 7 : i32
    %gather_index = tt.splat %bit : i32 -> tensor<1xi32, #one_hot_basis>
    %gathered = tt.gather %bases[%gather_index] {axis = 0 : i32, efficient_layout} : (tensor<32xi32, #one_hot_basis>, tensor<1xi32, #one_hot_basis>) -> tensor<1xi32, #one_hot_basis>
    %scalar = tt.unsplat %gathered : tensor<1xi32, #one_hot_basis>
    %broadcast = tt.splat %scalar : i32 -> tensor<128xi32, #one_hot_index>
    %zero = arith.constant dense<0> : tensor<128xi32, #one_hot_index>
    %condition = arith.cmpi ne, %index, %zero : tensor<128xi32, #one_hot_index>
    %contribution = arith.select %condition, %broadcast, %zero : tensor<128xi1, #one_hot_index>, tensor<128xi32, #one_hot_index>
    %result = arith.xori %index, %contribution : tensor<128xi32, #one_hot_index>
    tt.return %result : tensor<128xi32, #one_hot_index>
  }

  // A reused conditional contribution cannot disappear after fusion, so keep
  // both of its users unchanged while still optimizing the original reduction.
  // CHECK-LABEL: @one_hot_xor_shared_contribution
  // ONE-HOT-LABEL: @one_hot_xor_shared_contribution
  // ONE-HOT-NOT: "tt.reduce"
  // ONE-HOT: tt.gather
  // ONE-HOT: tt.unsplat
  // ONE-HOT: [[CONTRIBUTION:%.*]] = arith.select
  // ONE-HOT-NOT: tt.elementwise_inline_asm
  // ONE-HOT: [[XOR:%.*]] = arith.xori {{.*}}, [[CONTRIBUTION]]
  // ONE-HOT: arith.addi [[XOR]], [[CONTRIBUTION]]
  // ONE-HOT: tt.return
  tt.func @one_hot_xor_shared_contribution(%index: tensor<128xi32, #one_hot_index>, %bases: tensor<32xi32, #one_hot_basis>) -> tensor<128xi32, #one_hot_index> {
    %offsets = tt.make_range {start = 0 : i32, end = 32 : i32} : tensor<32xi32, #one_hot_basis>
    %bit = arith.constant dense<5> : tensor<32xi32, #one_hot_basis>
    %zero_basis = arith.constant dense<0> : tensor<32xi32, #one_hot_basis>
    %zero_index = arith.constant dense<0> : tensor<128xi32, #one_hot_index>
    %is_basis_bit = arith.cmpi eq, %offsets, %bit : tensor<32xi32, #one_hot_basis>
    %selected = arith.select %is_basis_bit, %bases, %zero_basis : tensor<32xi1, #one_hot_basis>, tensor<32xi32, #one_hot_basis>
    %reduced = "tt.reduce"(%selected) <{axis = 0 : i32}> ({
      ^bb0(%left: i32, %right: i32):
        %combined = arith.xori %left, %right : i32
        tt.reduce.return %combined : i32
    }) : (tensor<32xi32, #one_hot_basis>) -> i32
    %broadcast = tt.splat %reduced : i32 -> tensor<128xi32, #one_hot_index>
    %condition = arith.cmpi ne, %index, %zero_index : tensor<128xi32, #one_hot_index>
    %contribution = arith.select %condition, %broadcast, %zero_index : tensor<128xi1, #one_hot_index>, tensor<128xi32, #one_hot_index>
    %xor = arith.xori %index, %contribution : tensor<128xi32, #one_hot_index>
    %result = arith.addi %xor, %contribution : tensor<128xi32, #one_hot_index>
    tt.return %result : tensor<128xi32, #one_hot_index>
  }

  // The yielded combiner can still be XOR when earlier region operations have
  // observable effects. Replacing the reduction would incorrectly erase them.
  // CHECK-LABEL: @one_hot_xor_side_effectful_combiner
  // ONE-HOT-LABEL: @one_hot_xor_side_effectful_combiner
  // ONE-HOT-NOT: tt.gather
  // ONE-HOT: "tt.reduce"
  // ONE-HOT: tt.assert
  // ONE-HOT: arith.xori
  // ONE-HOT: tt.reduce.return
  // ONE-HOT: tt.return
  tt.func @one_hot_xor_side_effectful_combiner(%bases: tensor<32xi32, #one_hot_basis>) -> i32 {
    %offsets = tt.make_range {start = 0 : i32, end = 32 : i32} : tensor<32xi32, #one_hot_basis>
    %bit = arith.constant dense<7> : tensor<32xi32, #one_hot_basis>
    %zero = arith.constant dense<0> : tensor<32xi32, #one_hot_basis>
    %condition = arith.cmpi eq, %offsets, %bit : tensor<32xi32, #one_hot_basis>
    %selected = arith.select %condition, %bases, %zero : tensor<32xi1, #one_hot_basis>, tensor<32xi32, #one_hot_basis>
    %reduced = "tt.reduce"(%selected) <{axis = 0 : i32}> ({
      ^bb0(%left: i32, %right: i32):
        %valid = arith.cmpi ne, %left, %right : i32
        tt.assert %valid, "side effect must not disappear" : i1
        %combined = arith.xori %left, %right : i32
        tt.reduce.return %combined : i32
    }) : (tensor<32xi32, #one_hot_basis>) -> i32
    tt.return %reduced : i32
  }

  // More than one register value per lane would need register selection in
  // addition to the shuffle, so leave the original reduction unchanged.
  // CHECK-LABEL: @one_hot_xor_multiple_registers
  // ONE-HOT-LABEL: @one_hot_xor_multiple_registers
  // ONE-HOT-NOT: tt.gather
  // ONE-HOT: "tt.reduce"
  // ONE-HOT: tt.return
  tt.func @one_hot_xor_multiple_registers(%bases: tensor<32xi32, #one_hot_multiple_registers>) -> i32 {
    %offsets = tt.make_range {start = 0 : i32, end = 32 : i32} : tensor<32xi32, #one_hot_multiple_registers>
    %bit = arith.constant dense<4> : tensor<32xi32, #one_hot_multiple_registers>
    %zero = arith.constant dense<0> : tensor<32xi32, #one_hot_multiple_registers>
    %condition = arith.cmpi eq, %offsets, %bit : tensor<32xi32, #one_hot_multiple_registers>
    %selected = arith.select %condition, %bases, %zero : tensor<32xi1, #one_hot_multiple_registers>, tensor<32xi32, #one_hot_multiple_registers>
    %reduced = "tt.reduce"(%selected) <{axis = 0 : i32}> ({
      ^bb0(%left: i32, %right: i32):
        %combined = arith.xori %left, %right : i32
        tt.reduce.return %combined : i32
    }) : (tensor<32xi32, #one_hot_multiple_registers>) -> i32
    tt.return %reduced : i32
  }

  // A warp-local gather cannot fetch a basis value owned by another warp.
  // CHECK-LABEL: @one_hot_xor_cross_warp
  // ONE-HOT-LABEL: @one_hot_xor_cross_warp
  // ONE-HOT-NOT: tt.gather
  // ONE-HOT: "tt.reduce"
  // ONE-HOT: tt.return
  tt.func @one_hot_xor_cross_warp(%bases: tensor<32xi32, #one_hot_cross_warp>) -> i32 {
    %offsets = tt.make_range {start = 0 : i32, end = 32 : i32} : tensor<32xi32, #one_hot_cross_warp>
    %bit = arith.constant dense<4> : tensor<32xi32, #one_hot_cross_warp>
    %zero = arith.constant dense<0> : tensor<32xi32, #one_hot_cross_warp>
    %condition = arith.cmpi eq, %offsets, %bit : tensor<32xi32, #one_hot_cross_warp>
    %selected = arith.select %condition, %bases, %zero : tensor<32xi1, #one_hot_cross_warp>, tensor<32xi32, #one_hot_cross_warp>
    %reduced = "tt.reduce"(%selected) <{axis = 0 : i32}> ({
      ^bb0(%left: i32, %right: i32):
        %combined = arith.xori %left, %right : i32
        tt.reduce.return %combined : i32
    }) : (tensor<32xi32, #one_hot_cross_warp>) -> i32
    tt.return %reduced : i32
  }

  // A nonzero inactive lane breaks the one-hot reduction identity.
  // CHECK-LABEL: @one_hot_xor_nonzero_inactive
  // ONE-HOT-LABEL: @one_hot_xor_nonzero_inactive
  // ONE-HOT-NOT: tt.gather
  // ONE-HOT: "tt.reduce"
  // ONE-HOT: tt.return
  tt.func @one_hot_xor_nonzero_inactive(%bases: tensor<32xi32, #one_hot_basis>) -> i32 {
    %offsets = tt.make_range {start = 0 : i32, end = 32 : i32} : tensor<32xi32, #one_hot_basis>
    %bit = arith.constant dense<4> : tensor<32xi32, #one_hot_basis>
    %inactive = arith.constant dense<1> : tensor<32xi32, #one_hot_basis>
    %condition = arith.cmpi eq, %offsets, %bit : tensor<32xi32, #one_hot_basis>
    %selected = arith.select %condition, %bases, %inactive : tensor<32xi1, #one_hot_basis>, tensor<32xi32, #one_hot_basis>
    %reduced = "tt.reduce"(%selected) <{axis = 0 : i32}> ({
      ^bb0(%left: i32, %right: i32):
        %combined = arith.xori %left, %right : i32
        tt.reduce.return %combined : i32
    }) : (tensor<32xi32, #one_hot_basis>) -> i32
    tt.return %reduced : i32
  }

  // An out-of-range selected index has zero contribution, not the value of a
  // wrapped warp lane.
  // CHECK-LABEL: @one_hot_xor_out_of_range
  // ONE-HOT-LABEL: @one_hot_xor_out_of_range
  // ONE-HOT-NOT: tt.gather
  // ONE-HOT: "tt.reduce"
  // ONE-HOT: tt.return
  tt.func @one_hot_xor_out_of_range(%bases: tensor<32xi32, #one_hot_basis>) -> i32 {
    %offsets = tt.make_range {start = 0 : i32, end = 32 : i32} : tensor<32xi32, #one_hot_basis>
    %bit = arith.constant dense<32> : tensor<32xi32, #one_hot_basis>
    %zero = arith.constant dense<0> : tensor<32xi32, #one_hot_basis>
    %condition = arith.cmpi eq, %offsets, %bit : tensor<32xi32, #one_hot_basis>
    %selected = arith.select %condition, %bases, %zero : tensor<32xi1, #one_hot_basis>, tensor<32xi32, #one_hot_basis>
    %reduced = "tt.reduce"(%selected) <{axis = 0 : i32}> ({
      ^bb0(%left: i32, %right: i32):
        %combined = arith.xori %left, %right : i32
        tt.reduce.return %combined : i32
    }) : (tensor<32xi32, #one_hot_basis>) -> i32
    tt.return %reduced : i32
  }
}

// -----

#one_hot_cross_cta = #ttg.blocked<{sizePerThread = [1], threadsPerWarp = [32], warpsPerCTA = [4], order = [0], CGALayout = [[1]]}>

module attributes {"ttg.target" = "cuda:90", "ttg.num-ctas" = 2 : i32, "ttg.num-warps" = 4 : i32, "ttg.threads-per-warp" = 32 : i32} {
  // A warp shuffle cannot communicate a basis value across CTAs.
  // CHECK-LABEL: @one_hot_xor_cross_cta
  // ONE-HOT-LABEL: @one_hot_xor_cross_cta
  // ONE-HOT-NOT: tt.gather
  // ONE-HOT: "tt.reduce"
  // ONE-HOT: tt.return
  tt.func @one_hot_xor_cross_cta(%bases: tensor<32xi32, #one_hot_cross_cta>) -> i32 {
    %offsets = tt.make_range {start = 0 : i32, end = 32 : i32} : tensor<32xi32, #one_hot_cross_cta>
    %bit = arith.constant dense<3> : tensor<32xi32, #one_hot_cross_cta>
    %zero = arith.constant dense<0> : tensor<32xi32, #one_hot_cross_cta>
    %condition = arith.cmpi eq, %offsets, %bit : tensor<32xi32, #one_hot_cross_cta>
    %selected = arith.select %condition, %bases, %zero : tensor<32xi1, #one_hot_cross_cta>, tensor<32xi32, #one_hot_cross_cta>
    %reduced = "tt.reduce"(%selected) <{axis = 0 : i32}> ({
      ^bb0(%left: i32, %right: i32):
        %combined = arith.xori %left, %right : i32
        tt.reduce.return %combined : i32
    }) : (tensor<32xi32, #one_hot_cross_cta>) -> i32
    tt.return %reduced : i32
  }
}

// -----

#one_hot_amd = #ttg.blocked<{sizePerThread = [1], threadsPerWarp = [64], warpsPerCTA = [4], order = [0]}>

module attributes {"ttg.target" = "hip:gfx950", "ttg.num-ctas" = 1 : i32, "ttg.num-warps" = 4 : i32, "ttg.threads-per-warp" = 64 : i32} {
  // The optimization emits NVIDIA PTX and must never run on AMD targets.
  // CHECK-LABEL: @one_hot_xor_amd_unchanged
  // ONE-HOT-LABEL: @one_hot_xor_amd_unchanged
  // ONE-HOT-NOT: tt.gather
  // ONE-HOT: "tt.reduce"
  // ONE-HOT-NOT: tt.elementwise_inline_asm
  // ONE-HOT: tt.return
  tt.func @one_hot_xor_amd_unchanged(%bases: tensor<32xi32, #one_hot_amd>) -> i32 {
    %offsets = tt.make_range {start = 0 : i32, end = 32 : i32} : tensor<32xi32, #one_hot_amd>
    %bit = arith.constant dense<3> : tensor<32xi32, #one_hot_amd>
    %zero = arith.constant dense<0> : tensor<32xi32, #one_hot_amd>
    %condition = arith.cmpi eq, %offsets, %bit : tensor<32xi32, #one_hot_amd>
    %selected = arith.select %condition, %bases, %zero : tensor<32xi1, #one_hot_amd>, tensor<32xi32, #one_hot_amd>
    %reduced = "tt.reduce"(%selected) <{axis = 0 : i32}> ({
      ^bb0(%left: i32, %right: i32):
        %combined = arith.xori %left, %right : i32
        tt.reduce.return %combined : i32
    }) : (tensor<32xi32, #one_hot_amd>) -> i32
    tt.return %reduced : i32
  }
}
