
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Users/andrew/venvs/refusals/lib/python3.10/site-packages/cmake/data/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Darwin - 25.0.0 - arm64
...
