[project]
name = "triton_bench"
version = "1.0.0"
dependencies = ["torch", "numpy", "pytest"]

[build-system]
requires = ["setuptools>=64.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["triton_bench*"]
