// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// RUN: triton-opt %s -allow-unregistered-dialect -split-input-file -tritonamdgpu-canonicalize-pointers="enable-large-tensor-ptr-canon=true" | FileCheck %s

// Regression tests for a crash in TritonAMDGPUCanonicalizePointers when a
// block has multiple predecessors (e.g. both a cf.cond_br and a cf.br) that
// each pass a pointer as a block argument.
//
// Root cause: convertSimpleBlockSignature called applySignatureConversion on
// the same block twice.  The first call expanded the block from N args to N+1
// (splitting the pointer into base+offset).  The second call then looped over
// oldBlockTypes.size() == N+1 entries while remappedOperands only had N
// ValueRanges, causing an out-of-bounds ArrayRef assertion.
//
// Fix: track which blocks have already had their signature converted in a
// SmallPtrSet<Block*> (convertedBlocks) and skip the second
// applySignatureConversion while still updating fatPtrs from the new operands.

// Scalar pointer passed as a block argument from two different predecessors:
//   ^bb0 -> (cf.cond_br, false branch) -> ^bb2(ptr=arg0)
//   ^bb1 -> (cf.br)                    -> ^bb2(ptr=arg1)
// ^bb2 therefore has 2 preds; without the fix this crashed with an
// ArrayRef out-of-bounds assertion on the second call to
// convertSimpleBlockSignature.

// CHECK-LABEL:   tt.func @scalar_ptr_block_arg_two_predecessors(
// CHECK-SAME:  %[[VAL_0:.*]]: !tt.ptr<f32>, %[[VAL_1:.*]]: !tt.ptr<f32>, %[[VAL_2:.*]]: i1) -> f32 {
// CHECK:           %[[VAL_3:.*]] = arith.constant 0 : i64
// CHECK:           %[[VAL_4:.*]] = arith.constant 0 : i64
// CHECK:           cf.cond_br %[[VAL_2]], ^bb1, ^bb2(%[[VAL_0]], %[[VAL_3]] : !tt.ptr<f32>, i64)
// CHECK:         ^bb1:
// CHECK:           cf.br ^bb2(%[[VAL_1]], %[[VAL_4]] : !tt.ptr<f32>, i64)
// CHECK:         ^bb2(%[[VAL_5:.*]]: !tt.ptr<f32>, %[[VAL_6:.*]]: i64):
// CHECK:           %[[VAL_7:.*]] = tt.addptr %[[VAL_5]], %[[VAL_6]] : !tt.ptr<f32>, i64
// CHECK:           %[[VAL_8:.*]] = tt.load %[[VAL_7]] : !tt.ptr<f32>
// CHECK:           tt.return %[[VAL_8]] : f32
// CHECK:         }

module attributes {"ttg.num-warps" = 4 : i32} {
  tt.func @scalar_ptr_block_arg_two_predecessors(%arg0: !tt.ptr<f32>, %arg1: !tt.ptr<f32>, %arg2: i1) -> f32 {
    cf.cond_br %arg2, ^bb1, ^bb2(%arg0 : !tt.ptr<f32>)
  ^bb1:  // pred: ^bb0 (true branch of cond_br)
    cf.br ^bb2(%arg1 : !tt.ptr<f32>)
  ^bb2(%0: !tt.ptr<f32>):  // 2 preds: ^bb0 (false branch), ^bb1
    %1 = tt.load %0 : !tt.ptr<f32>
    tt.return %1 : f32
  }
}

// -----

// Tensor pointer passed as a block argument from two different predecessors.
// Same pattern as above but with tensor<1024x!tt.ptr<f32>> to exercise the
// tensor-pointer split path in addition to the scalar path.

// CHECK-LABEL:   tt.func @tensor_ptr_block_arg_two_predecessors(
// CHECK-SAME:  %[[VAL_0:.*]]: !tt.ptr<f32>, %[[VAL_1:.*]]: i1) -> tensor<1024xf32> {
// CHECK:           %[[VAL_2:.*]] = arith.constant 0 : i64
// CHECK:           %[[VAL_3:.*]] = arith.constant 1024 : i32
// CHECK:           %[[VAL_4:.*]] = tt.get_program_id x : i32
// CHECK:           %[[VAL_5:.*]] = arith.muli %[[VAL_4]], %[[VAL_3]] : i32
// CHECK:           %[[VAL_6:.*]] = tt.make_range {end = 1024 : i32, start = 0 : i32} : tensor<1024xi32>
// CHECK:           %[[VAL_7:.*]] = tt.splat %[[VAL_2]] : i64 -> tensor<1024xi64>
// CHECK:           %[[VAL_8:.*]] = tt.addptr %[[VAL_0]], %[[VAL_5]] : !tt.ptr<f32>, i32
// CHECK:           %[[VAL_9:.*]] = arith.extsi %[[VAL_6]] : tensor<1024xi32> to tensor<1024xi64>
// CHECK:           cf.cond_br %[[VAL_1]], ^bb1, ^bb2(%[[VAL_8]], %[[VAL_9]] : !tt.ptr<f32>, tensor<1024xi64>)
// CHECK:         ^bb1:
// CHECK:           cf.br ^bb2(%[[VAL_0]], %[[VAL_7]] : !tt.ptr<f32>, tensor<1024xi64>)
// CHECK:         ^bb2(%[[VAL_10:.*]]: !tt.ptr<f32>, %[[VAL_11:.*]]: tensor<1024xi64>):
// CHECK:           %[[VAL_12:.*]] = arith.trunci %[[VAL_11]] : tensor<1024xi64> to tensor<1024xi32>
// CHECK:           %[[VAL_13:.*]] = tt.splat %[[VAL_10]] : !tt.ptr<f32> -> tensor<1024x!tt.ptr<f32>>
// CHECK:           %[[VAL_14:.*]] = tt.addptr %[[VAL_13]], %[[VAL_12]] : tensor<1024x!tt.ptr<f32>>, tensor<1024xi32>
// CHECK:           %[[VAL_15:.*]] = tt.load %[[VAL_14]] : tensor<1024x!tt.ptr<f32>>
// CHECK:           tt.return %[[VAL_15]] : tensor<1024xf32>
// CHECK:         }

module attributes {"ttg.num-warps" = 4 : i32} {
  tt.func @tensor_ptr_block_arg_two_predecessors(%arg0: !tt.ptr<f32>, %arg1: i1) -> tensor<1024xf32> {
    %c1024_i32 = arith.constant 1024 : i32
    %0 = tt.get_program_id x : i32
    %1 = arith.muli %0, %c1024_i32 : i32
    %2 = tt.make_range {end = 1024 : i32, start = 0 : i32} : tensor<1024xi32>
    %3 = tt.splat %1 : i32 -> tensor<1024xi32>
    %4 = arith.addi %3, %2 : tensor<1024xi32>
    %5 = tt.splat %arg0 : !tt.ptr<f32> -> tensor<1024x!tt.ptr<f32>>
    %6 = tt.addptr %5, %4 : tensor<1024x!tt.ptr<f32>>, tensor<1024xi32>
    cf.cond_br %arg1, ^bb1, ^bb2(%6 : tensor<1024x!tt.ptr<f32>>)
  ^bb1:  // pred: ^bb0 (true branch)
    cf.br ^bb2(%5 : tensor<1024x!tt.ptr<f32>>)
  ^bb2(%7: tensor<1024x!tt.ptr<f32>>):  // 2 preds: ^bb0 (false branch), ^bb1
    %8 = tt.load %7 : tensor<1024x!tt.ptr<f32>>
    tt.return %8 : tensor<1024xf32>
  }
}
