// NOTE: Assertions have been autogenerated by mlir/utils/generate-test-checks.py

// RUN: triton-opt %s -allow-unregistered-dialect -split-input-file -tritonamdgpu-canonicalize-pointers="enable-large-tensor-ptr-canon=true" -verify-diagnostics | FileCheck %s

module attributes {"ttg.num-warps" = 4 : i32} {
  tt.func @ifOpTwoYields(%arg0: !tt.ptr<f32>, %arg1: tensor<1024xf32>, %arg2: i1) -> (tensor<1024xf32>, tensor<1024xf32>) {
    %c1024_i32 = arith.constant 1024 : i32
    %0 = tt.get_program_id x : i32
    %1 = arith.muli %0, %c1024_i32 : i32
    %2 = tt.make_range {end = 1024 : i32, start = 0 : i32} : tensor<1024xi32>
    %3 = tt.splat %1 : i32 -> tensor<1024xi32>
    %4 = arith.addi %3, %2 : tensor<1024xi32>
    %5 = tt.splat %arg0 : !tt.ptr<f32> -> tensor<1024x!tt.ptr<f32>>
    %6:2 = scf.if %arg2 -> (tensor<1024x!tt.ptr<f32>>, tensor<1024x!tt.ptr<f32>>) {
      %8 = tt.addptr %5, %4 : tensor<1024x!tt.ptr<f32>>, tensor<1024xi32>
      scf.yield %8, %8 : tensor<1024x!tt.ptr<f32>>, tensor<1024x!tt.ptr<f32>>
    } else {
      %8 = tt.addptr %5, %3 : tensor<1024x!tt.ptr<f32>>, tensor<1024xi32>
      scf.yield %8, %8 : tensor<1024x!tt.ptr<f32>>, tensor<1024x!tt.ptr<f32>>
    }
    %7 = tt.load %6#0 : tensor<1024x!tt.ptr<f32>>
    %8 = tt.load %6#1 : tensor<1024x!tt.ptr<f32>>
    tt.return %7, %8 : tensor<1024xf32>, tensor<1024xf32>
  }
}

// CHECK-LABEL:  tt.func @ifOpTwoYields(
// CHECK-SAME:        %arg0: !tt.ptr<f32>,
// CHECK-SAME:        %arg1: tensor<1024xf32>,
// CHECK-SAME:        %arg2: i1) -> (tensor<1024xf32>, tensor<1024xf32>) {
// CHECK:           %[[const0:.*]] = arith.constant 0 : i64
// CHECK:           %[[C1024:.*]] = arith.constant 1024 : i32
// CHECK:           %[[PID:.*]] = tt.get_program_id x : i32
// CHECK:           %[[PID_time_1024:.*]] = arith.muli %[[PID]], %[[C1024]] : i32
// CHECK:           %[[MAKE_RANGE_1024:.*]] = tt.make_range {end = 1024 : i32, start = 0 : i32} : tensor<1024xi32>
// CHECK:           %[[CONST_ZERO_SPLAT:.*]] = tt.splat %[[const0]] : i64 -> tensor<1024xi64>
// CHECK:           %[[SCF:.*]]:4 = scf.if %arg2 -> (!tt.ptr<f32>, tensor<1024xi64>, !tt.ptr<f32>, tensor<1024xi64>) {
// CHECK:             %[[ADDPTR1:.*]] = tt.addptr %arg0, %[[PID_time_1024]] : !tt.ptr<f32>, i32
// CHECK:             %[[EXT_RANGE:.*]] = arith.extsi %[[MAKE_RANGE_1024]] : tensor<1024xi32> to tensor<1024xi64>
// CHECK:             scf.yield %[[ADDPTR1]], %[[EXT_RANGE]], %[[ADDPTR1]], %[[EXT_RANGE]] : !tt.ptr<f32>, tensor<1024xi64>, !tt.ptr<f32>, tensor<1024xi64>
//                  } else {
// CHECK:             %[[ADDPTR2:.*]] = tt.addptr %arg0, %[[PID_time_1024]] : !tt.ptr<f32>, i32
// CHECK:             scf.yield %[[ADDPTR2]], %[[CONST_ZERO_SPLAT]], %[[ADDPTR2]], %[[CONST_ZERO_SPLAT]] : !tt.ptr<f32>, tensor<1024xi64>, !tt.ptr<f32>, tensor<1024xi64>
//                  }
// CHECK:           %[[dont_care_5:.*]] = arith.trunci %[[SCF]]#1 : tensor<1024xi64> to tensor<1024xi32>
// CHECK:           %[[dont_care_6:.*]] = tt.splat %[[SCF]]#0 : !tt.ptr<f32> -> tensor<1024x!tt.ptr<f32>>
// CHECK:           %[[dont_care_7:.*]] = tt.addptr %[[dont_care_6]], %[[dont_care_5]] : tensor<1024x!tt.ptr<f32>>, tensor<1024xi32>
// CHECK:           %[[dont_care_8:.*]] = tt.load %[[dont_care_7]] : tensor<1024x!tt.ptr<f32>>
// CHECK:           %[[dont_care_9:.*]] = arith.trunci %[[SCF]]#3 : tensor<1024xi64> to tensor<1024xi32>
// CHECK:           %[[dont_care_10:.*]] = tt.splat %[[SCF]]#2 : !tt.ptr<f32> -> tensor<1024x!tt.ptr<f32>>
// CHECK:           %[[dont_care_11:.*]] = tt.addptr %[[dont_care_10]], %[[dont_care_9]] : tensor<1024x!tt.ptr<f32>>, tensor<1024xi32>
// CHECK:           %[[dont_care_12:.*]] = tt.load %[[dont_care_11]] : tensor<1024x!tt.ptr<f32>>
// CHECK:           tt.return %[[dont_care_8]], %[[dont_care_12]] : tensor<1024xf32>, tensor<1024xf32>

// -----

module attributes {"ttg.num-warps" = 4 : i32} {
  tt.func @ifOpTwoYieldsAndNonPtr(%arg0: !tt.ptr<f32>, %arg1: tensor<1024xf32>, %arg2: i1) -> (tensor<1024xf32>, tensor<1024xf32>, i32) {
    %c1024_i32 = arith.constant 1024 : i32
    %0 = tt.get_program_id x : i32
    %1 = arith.muli %0, %c1024_i32 : i32
    %2 = tt.make_range {end = 1024 : i32, start = 0 : i32} : tensor<1024xi32>
    %3 = tt.splat %1 : i32 -> tensor<1024xi32>
    %4 = arith.addi %3, %2 : tensor<1024xi32>
    %5 = tt.splat %arg0 : !tt.ptr<f32> -> tensor<1024x!tt.ptr<f32>>
    %6:3 = scf.if %arg2 -> (tensor<1024x!tt.ptr<f32>>, tensor<1024x!tt.ptr<f32>>, i32) {
      %8 = tt.addptr %5, %4 : tensor<1024x!tt.ptr<f32>>, tensor<1024xi32>
      scf.yield %8, %8, %0 : tensor<1024x!tt.ptr<f32>>, tensor<1024x!tt.ptr<f32>>, i32
    } else {
      %8 = tt.addptr %5, %3 : tensor<1024x!tt.ptr<f32>>, tensor<1024xi32>
      %9 = arith.muli %1, %1 : i32
      scf.yield %8, %8, %9 : tensor<1024x!tt.ptr<f32>>, tensor<1024x!tt.ptr<f32>>, i32
    }
    %7 = tt.load %6#0 : tensor<1024x!tt.ptr<f32>>
    %8 = tt.load %6#1 : tensor<1024x!tt.ptr<f32>>
    tt.return %7, %8, %6#2 : tensor<1024xf32>, tensor<1024xf32>, i32
  }
}

// CHECK-LABEL:   tt.func @ifOpTwoYieldsAndNonPtr(
// CHECK-SAME:        %arg0: !tt.ptr<f32>,
// CHECK-SAME:        %arg1: tensor<1024xf32>,
// CHECK-SAME:        %arg2: i1) -> (tensor<1024xf32>, tensor<1024xf32>, i32) {
// CHECK-DAG:         %c0_i64 = arith.constant 0 : i64
// CHECK:             %[[C1024:.*]] = arith.constant 1024 : i32
// CHECK:             %[[PID:.*]] = tt.get_program_id x : i32
// CHECK:             %[[PID_TIME_1024:.*]] = arith.muli %[[PID]], %[[C1024]] : i32
// CHECK:             %[[MK_RANGE:.*]] = tt.make_range {end = 1024 : i32, start = 0 : i32} : tensor<1024xi32>
// CHECK:             %[[CONST0_SPLAT:.*]] = tt.splat %c0_i64 : i64 -> tensor<1024xi64>
// CHECK:             %[[SCF_IF:.*]]:5 = scf.if %arg2 -> (!tt.ptr<f32>, tensor<1024xi64>, !tt.ptr<f32>, tensor<1024xi64>, i32) {
// CHECK:               %[[PTR_BASE_0:.*]] = tt.addptr %arg0, %[[PID_TIME_1024]] : !tt.ptr<f32>, i32
// CHECK:               %[[EXT_MK_RANGE:.*]] = arith.extsi %[[MK_RANGE]] : tensor<1024xi32> to tensor<1024xi64>
// CHECK:               scf.yield %[[PTR_BASE_0]], %[[EXT_MK_RANGE]], %[[PTR_BASE_0]], %[[EXT_MK_RANGE]], %[[PID]] : !tt.ptr<f32>, tensor<1024xi64>, !tt.ptr<f32>, tensor<1024xi64>, i32
//                  } else {
// CHECK:               %[[BASE_PTR_1:.*]] = tt.addptr %arg0, %[[PID_TIME_1024]] : !tt.ptr<f32>, i32
// CHECK:               %[[OFST_2:.*]] = arith.muli %[[PID_TIME_1024]], %[[PID_TIME_1024]] : i32
//                      scf.yield %[[BASE_PTR_1]], %[[CONST0_SPLAT]], %[[BASE_PTR_1]], %[[CONST0_SPLAT]], %[[OFST_2]] : !tt.ptr<f32>, tensor<1024xi64>, !tt.ptr<f32>, tensor<1024xi64>, i32
//                  }
// CHECK:          %[[dont_care_5:.*]] = arith.trunci %[[SCF_IF]]#1 : tensor<1024xi64> to tensor<1024xi32>
// CHECK:          %[[dont_care_6:.*]] = tt.splat %[[SCF_IF]]#0 : !tt.ptr<f32> -> tensor<1024x!tt.ptr<f32>>
// CHECK:          %[[dont_care_7:.*]] = tt.addptr %[[dont_care_6]], %[[dont_care_5]] : tensor<1024x!tt.ptr<f32>>, tensor<1024xi32>
// CHECK:          %[[dont_care_8:.*]] = tt.load %[[dont_care_7]] : tensor<1024x!tt.ptr<f32>>
// CHECK:          %[[dont_care_9:.*]] = arith.trunci %[[SCF_IF]]#3 : tensor<1024xi64> to tensor<1024xi32>
// CHECK:          %[[dont_care_10:.*]] = tt.splat %[[SCF_IF]]#2 : !tt.ptr<f32> -> tensor<1024x!tt.ptr<f32>>
// CHECK:          %[[dont_care_11:.*]] = tt.addptr %[[dont_care_10]], %[[dont_care_9]] : tensor<1024x!tt.ptr<f32>>, tensor<1024xi32>
// CHECK:          %[[dont_care_12:.*]] = tt.load %[[dont_care_11]] : tensor<1024x!tt.ptr<f32>>
// CHECK:          tt.return %[[dont_care_8]], %[[dont_care_12]], %[[SCF_IF]]#4 : tensor<1024xf32>, tensor<1024xf32>, i32

// -----

module attributes {"ttg.num-warps" = 4 : i32} {
  tt.func @ifOpTwoYieldsAndNonPtrReordered(%arg0: !tt.ptr<f32>, %arg1: tensor<1024xf32>, %arg2: i1) -> (tensor<1024xf32>, tensor<1024xf32>, i32) {
    %c1024_i32 = arith.constant 1024 : i32
    %0 = tt.get_program_id x : i32
    %1 = arith.muli %0, %c1024_i32 : i32
    %2 = tt.make_range {end = 1024 : i32, start = 0 : i32} : tensor<1024xi32>
    %3 = tt.splat %1 : i32 -> tensor<1024xi32>
    %4 = arith.addi %3, %2 : tensor<1024xi32>
    %5 = tt.splat %arg0 : !tt.ptr<f32> -> tensor<1024x!tt.ptr<f32>>
    %6:3 = scf.if %arg2 -> (tensor<1024x!tt.ptr<f32>>, i32, tensor<1024x!tt.ptr<f32>>) {
      %8 = tt.addptr %5, %4 : tensor<1024x!tt.ptr<f32>>, tensor<1024xi32>
      scf.yield %8, %0, %8 : tensor<1024x!tt.ptr<f32>>, i32, tensor<1024x!tt.ptr<f32>>
    } else {
      %8 = tt.addptr %5, %3 : tensor<1024x!tt.ptr<f32>>, tensor<1024xi32>
      %9 = arith.muli %1, %1 : i32
      scf.yield %8, %9, %8 : tensor<1024x!tt.ptr<f32>>, i32, tensor<1024x!tt.ptr<f32>>
    }
    %7 = tt.load %6#0 : tensor<1024x!tt.ptr<f32>>
    %8 = tt.load %6#2 : tensor<1024x!tt.ptr<f32>>
    tt.return %7, %8, %6#1 : tensor<1024xf32>, tensor<1024xf32>, i32
  }
}

// CHECK-LABEL:   tt.func @ifOpTwoYieldsAndNonPtrReordered(
// CHECK-SAME:        %arg0: !tt.ptr<f32>,
// CHECK-SAME:        %arg1: tensor<1024xf32>,
// CHECK-SAME:        %arg2: i1) -> (tensor<1024xf32>, tensor<1024xf32>, i32) {
// CHECK:           %[[C0:.*]] = arith.constant 0 : i64
// CHECK:           %[[C1024:.*]] = arith.constant 1024 : i32
// CHECK:           %[[PID:.*]] = tt.get_program_id x : i32
// CHECK:           %[[PID_TIME_1024:.*]] = arith.muli %[[PID]], %[[C1024]] : i32
// CHECK:           %[[MK_RANGE_1024:.*]] = tt.make_range {end = 1024 : i32, start = 0 : i32} : tensor<1024xi32>
// CHECK:           %[[C0_SPLAT:.*]] = tt.splat %[[C0]] : i64 -> tensor<1024xi64>
// CHECK:           %[[SCF_IF:.*]]:5 = scf.if %arg2 -> (!tt.ptr<f32>, tensor<1024xi64>, i32, !tt.ptr<f32>, tensor<1024xi64>) {
// CHECK:             %[[PTR_BASE_1:.*]] = tt.addptr %arg0, %[[PID_TIME_1024]] : !tt.ptr<f32>, i32
// CHECK:             %[[EXT_MK_RANGE:.*]] = arith.extsi %[[MK_RANGE_1024]] : tensor<1024xi32> to tensor<1024xi64>
// CHECK:             scf.yield %[[PTR_BASE_1]], %[[EXT_MK_RANGE]], %[[PID]], %[[PTR_BASE_1]], %[[EXT_MK_RANGE]] : !tt.ptr<f32>, tensor<1024xi64>, i32, !tt.ptr<f32>, tensor<1024xi64>
//                  } else {
// CHECK:             %[[PTR_BASE_2:.*]] = tt.addptr %arg0, %[[PID_TIME_1024]] : !tt.ptr<f32>, i32
// CHECK:             %[[EXT_MK_RANGE:.*]] = arith.muli %[[PID_TIME_1024]], %[[PID_TIME_1024]] : i32
// CHECK:             scf.yield %[[PTR_BASE_2]], %[[C0_SPLAT]], %[[EXT_MK_RANGE]], %[[PTR_BASE_2]], %[[C0_SPLAT]] : !tt.ptr<f32>, tensor<1024xi64>, i32, !tt.ptr<f32>, tensor<1024xi64>
//                  }
// CHECK:           %[[dont_care_5:.*]] = arith.trunci %[[SCF_IF]]#1 : tensor<1024xi64> to tensor<1024xi32>
// CHECK:           %[[dont_care_6:.*]] = tt.splat %[[SCF_IF]]#0 : !tt.ptr<f32> -> tensor<1024x!tt.ptr<f32>>
// CHECK:           %[[dont_care_7:.*]] = tt.addptr %[[dont_care_6]], %[[dont_care_5]] : tensor<1024x!tt.ptr<f32>>, tensor<1024xi32>
// CHECK:           %[[dont_care_8:.*]] = tt.load %[[dont_care_7]] : tensor<1024x!tt.ptr<f32>>
// CHECK:           %[[dont_care_9:.*]] = arith.trunci %[[SCF_IF]]#4 : tensor<1024xi64> to tensor<1024xi32>
// CHECK:           %[[dont_care_10:.*]] = tt.splat %[[SCF_IF]]#3 : !tt.ptr<f32> -> tensor<1024x!tt.ptr<f32>>
// CHECK:           %[[dont_care_11:.*]] = tt.addptr %[[dont_care_10]], %[[dont_care_9]] : tensor<1024x!tt.ptr<f32>>, tensor<1024xi32>
// CHECK:           %[[dont_care_12:.*]] = tt.load %[[dont_care_11]] : tensor<1024x!tt.ptr<f32>>
// CHECK:           tt.return %[[dont_care_8]], %[[dont_care_12]], %[[SCF_IF]]#2 : tensor<1024xf32>, tensor<1024xf32>, i32

// -----

module attributes {"ttg.num-warps" = 4 : i32} {
  tt.func @make_tensor_descriptor(%arg0: !tt.ptr<f32> {tt.divisibility = 16 : i32, tt.pointer_range = 32 : i32}, %n: i32 {tt.divisibility = 16 : i32}) -> !tt.tensordesc<16xf32> {
    %c1_i64 = arith.constant 1 : i64
    %c1_i32 = arith.constant 1 : i32
    %ptr = tt.addptr %arg0, %c1_i32 : !tt.ptr<f32>, i32
    %desc = tt.make_tensor_descriptor %ptr, [%n], [%c1_i64] : !tt.ptr<f32>, !tt.tensordesc<16xf32>
    tt.return %desc : !tt.tensordesc<16xf32>
  }
}

// CHECK-LABEL:   tt.func @make_tensor_descriptor(
// CHECK-SAME:  %[[VAL_0:.*]]: !tt.ptr<f32> {tt.divisibility = 16 : i32, tt.pointer_range = 32 : i32}, %[[VAL_1:.*]]: i32 {tt.divisibility = 16 : i32}) -> !tt.tensordesc<16xf32> {
// CHECK:           %[[VAL_2:.*]] = arith.constant 1 : i64
// CHECK:           %[[VAL_3:.*]] = arith.constant 1 : i32
// CHECK:           %[[VAL_4:.*]] = tt.addptr %[[VAL_0]], %[[VAL_3]] : !tt.ptr<f32>, i32
// CHECK:           %[[VAL_5:.*]] = tt.make_tensor_descriptor %[[VAL_4]], {{\[}}%[[VAL_1]]], {{\[}}%[[VAL_2]]] : <f32>, <16xf32>
// CHECK:           tt.return %[[VAL_5]] : !tt.tensordesc<16xf32>
// CHECK:         }

// -----

// CHECK-LABEL:   tt.func @scalar_ptr_block_arg_two_predecessors(
// CHECK:           cf.cond_br {{.*}}, ^bb1, ^bb2({{.*}} : !tt.ptr<f32>, i64)
// CHECK:         ^bb1:
// CHECK:           cf.br ^bb2({{.*}} : !tt.ptr<f32>, i64)
// CHECK:         ^bb2({{.*}}: !tt.ptr<f32>, {{.*}}: i64):

module attributes {"ttg.num-warps" = 4 : i32} {
  tt.func @scalar_ptr_block_arg_two_predecessors(%arg0: !tt.ptr<f32>, %arg1: !tt.ptr<f32>, %arg2: i1) -> f32 {
    cf.cond_br %arg2, ^bb1, ^bb2(%arg0 : !tt.ptr<f32>)
  ^bb1:  // pred: ^bb0 (true branch of cond_br)
    cf.br ^bb2(%arg1 : !tt.ptr<f32>)
  ^bb2(%0: !tt.ptr<f32>):  // 2 preds: ^bb0 (false branch), ^bb1
    %1 = tt.load %0 : !tt.ptr<f32>
    tt.return %1 : f32
  }
}
