#!/usr/bin/env sh

set -e

OUT="python/pyproject.toml"
IN="$OUT.in"
echo "# AUTOGENERATED by pre-commit, modify the .in file instead." > "$OUT"
echo >> "$OUT"
cat "$IN" >> "$OUT"
echo >> "$OUT"
echo "# From root pyproject.yaml" >> "$OUT"
cat "pyproject.toml" >> "$OUT"
