from typing import List, Tuple

from . import ir, runtime

def add_external_libs(arg0: ir.module, arg1: List[str], arg2: List[str]) -> None: ...
def compile_ptx_to_cubin(arg0: str, arg1: str, arg2: int) -> object: ...
def get_shared_memory_size(arg0: ir.module) -> int: ...
def set_rocm() -> None: ...
def translate_llvmir_to_hsaco(arg0: str, arg1: str, arg2: str, arg3: str) -> Tuple[str, str]: ...
def translate_llvmir_to_ptx(arg0: str, arg1: int, arg2: int) -> str: ...
def translate_triton_gpu_to_llvmir(arg0: ir.module, arg1: int) -> str: ...
