// Copyright 2021 The IREE Authors
//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#ifndef PYTHON_BINDINGS_TRITON_OPS
#define PYTHON_BINDINGS_TRITON_OPS

include "mlir/Bindings/Python/Attributes.td"
include "triton/Dialect/Triton/IR/TritonOps.td"

#endif // PYTHON_BINDINGS_TRITON_OPS
