file(GLOB CLBLAS_ROOT /opt/clBLAS*)

set(CLBLAS_INCLUDE_HINTS "${CLBLAS_ROOT}/include")
set(CLBLAS_LIBRARIES_HINTS "${CLBLAS_ROOT}/lib64")

find_path(CLBLAS_INCLUDE_DIR clBLAS.h HINTS ${CLBLAS_INCLUDE_HINTS})
find_library(CLBLAS_LIBRARIES NAMES clBLAS HINTS ${CLBLAS_LIBRARIES_HINTS})

if(CLBLAS_LIBRARIES)
    set(CLBLAS_LIBRARIES ${CLBLAS_LIBRARIES})
endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(CLBLAS  DEFAULT_MSG CLBLAS_LIBRARIES CLBLAS_INCLUDE_DIR)
mark_as_advanced(CLBLAS)
