file(GLOB CLAMDBLAS_ROOT /opt/clBlas*)

set(CLAMDBLAS_INCLUDE_HINTS "${CLAMDBLAS_ROOT}/include")
set(CLAMDBLAS_LIBRARIES_HINTS "${CLAMDBLAS_ROOT}/lib64")

find_path(CLAMDBLAS_INCLUDE_DIR clBLAS.h HINTS ${CLAMDBLAS_INCLUDE_HINTS})
find_library(CLAMDBLAS_LIBRARIES NAMES clBLAS HINTS ${CLAMDBLAS_LIBRARIES_HINTS})

if(CLAMDBLAS_LIBRARIES)
    set(CLAMDBLAS_LIBRARIES ${CLAMDBLAS_LIBRARIES})
endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(CLAMDBLAS  DEFAULT_MSG CLAMDBLAS_LIBRARIES CLAMDBLAS_INCLUDE_DIR)
mark_as_advanced(CLAMDBLAS)
