; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --tool triton-llvm-opt --check-inst-comments --version 5
; RUN: triton-llvm-opt -scalarize-packed-fops %s | FileCheck %s
; RUN: triton-llvm-opt -scalarize-packed-fops %s | llc -mtriple=nvptx64 -mcpu=sm_100 -fp-contract=fast | FileCheck %s --check-prefix=PTX
; RUN: triton-llvm-opt -scalarize-packed-fops %s | llc -mtriple=nvptx64 -mcpu=sm_100 -fp-contract=off | FileCheck %s --check-prefix=NOFUSE

; Scalarize half-used FP32 pairs while retaining fully used pairs, including
; within wider SLP vectors.
declare <2 x float> @llvm.fma.v2f32(<2 x float>, <2 x float>, <2 x float>)
declare <4 x float> @llvm.fma.v4f32(<4 x float>, <4 x float>, <4 x float>)
declare <2 x half> @llvm.fma.v2f16(<2 x half>, <2 x half>, <2 x half>)
declare <2 x float> @llvm.fmuladd.v2f32(<2 x float>, <2 x float>, <2 x float>)
declare <2 x float> @llvm.experimental.constrained.fma.v2f32(<2 x float>, <2 x float>, <2 x float>, metadata, metadata)

define float @fma_low(<2 x float> %a, <2 x float> %b, <2 x float> %c) {
; CHECK-LABEL: define float @fma_low(
; CHECK-SAME: <2 x float> [[A:%.*]], <2 x float> [[B:%.*]], <2 x float> [[C:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = extractelement <2 x float> [[A]], i64 0
; CHECK-NEXT:    [[TMP2:%.*]] = extractelement <2 x float> [[B]], i64 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x float> [[C]], i64 0
; CHECK-NEXT:    [[R:%.*]] = call float @llvm.fma.f32(float [[TMP1]], float [[TMP2]], float [[TMP3]])
; CHECK-NEXT:    ret float [[R]]
;
  %v = call <2 x float> @llvm.fma.v2f32(<2 x float> %a, <2 x float> %b, <2 x float> %c)
  %r = extractelement <2 x float> %v, i32 0
  ret float %r
}

define float @fma_high_flags(<2 x float> %a, <2 x float> %b, <2 x float> %c) {
; CHECK-LABEL: define float @fma_high_flags(
; CHECK-SAME: <2 x float> [[A:%.*]], <2 x float> [[B:%.*]], <2 x float> [[C:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = extractelement <2 x float> [[A]], i64 1
; CHECK-NEXT:    [[TMP2:%.*]] = extractelement <2 x float> [[B]], i64 1
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x float> [[C]], i64 1
; CHECK-NEXT:    [[R:%.*]] = call nnan nsz contract float @llvm.fma.f32(float [[TMP1]], float [[TMP2]], float [[TMP3]])
; CHECK-NEXT:    ret float [[R]]
;
  %v = call nnan nsz contract <2 x float> @llvm.fma.v2f32(<2 x float> %a, <2 x float> %b, <2 x float> %c)
  %r = extractelement <2 x float> %v, i64 1
  ret float %r
}

define float @arithmetic_chain(<2 x float> %a, <2 x float> %b, <2 x float> %c) {
; CHECK-LABEL: define float @arithmetic_chain(
; CHECK-SAME: <2 x float> [[A:%.*]], <2 x float> [[B:%.*]], <2 x float> [[C:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = extractelement <2 x float> [[A]], i64 0
; CHECK-NEXT:    [[TMP2:%.*]] = fneg float [[TMP1]]
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x float> [[B]], i64 0
; CHECK-NEXT:    [[TMP4:%.*]] = fmul contract float [[TMP2]], [[TMP3]]
; CHECK-NEXT:    [[TMP5:%.*]] = extractelement <2 x float> [[C]], i64 0
; CHECK-NEXT:    [[TMP6:%.*]] = fsub float [[TMP4]], [[TMP5]]
; CHECK-NEXT:    [[TMP7:%.*]] = extractelement <2 x float> [[B]], i64 0
; CHECK-NEXT:    [[TMP8:%.*]] = fadd float [[TMP6]], [[TMP7]]
; CHECK-NEXT:    [[TMP9:%.*]] = extractelement <2 x float> [[C]], i64 0
; CHECK-NEXT:    [[TMP10:%.*]] = fdiv float [[TMP8]], [[TMP9]]
; CHECK-NEXT:    [[TMP11:%.*]] = extractelement <2 x float> [[A]], i64 0
; CHECK-NEXT:    [[TMP12:%.*]] = frem float [[TMP10]], [[TMP11]]
; CHECK-NEXT:    ret float [[TMP12]]
;
  %neg = fneg <2 x float> %a
  %mul = fmul contract <2 x float> %neg, %b
  %sub = fsub <2 x float> %mul, %c
  %add = fadd <2 x float> %sub, %b
  %div = fdiv <2 x float> %add, %c
  %rem = frem <2 x float> %div, %a
  %r = extractelement <2 x float> %rem, i64 0
  ret float %r
}

define float @fma_chain(<2 x float> %a, <2 x float> %b, <2 x float> %c) {
; CHECK-LABEL: define float @fma_chain(
; CHECK-SAME: <2 x float> [[A:%.*]], <2 x float> [[B:%.*]], <2 x float> [[C:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = extractelement <2 x float> [[A]], i64 1
; CHECK-NEXT:    [[TMP2:%.*]] = extractelement <2 x float> [[B]], i64 1
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x float> [[C]], i64 1
; CHECK-NEXT:    [[TMP4:%.*]] = call float @llvm.fma.f32(float [[TMP1]], float [[TMP2]], float [[TMP3]])
; CHECK-NEXT:    [[TMP5:%.*]] = extractelement <2 x float> [[A]], i64 1
; CHECK-NEXT:    [[TMP6:%.*]] = fmul float [[TMP4]], [[TMP5]]
; CHECK-NEXT:    ret float [[TMP6]]
;
  %v = call <2 x float> @llvm.fma.v2f32(<2 x float> %a, <2 x float> %b, <2 x float> %c)
  %mul = fmul <2 x float> %v, %a
  %r = extractelement <2 x float> %mul, i32 1
  ret float %r
}

define <2 x float> @same_lane_users(<2 x float> %a, <2 x float> %b, <2 x float> %c) {
; CHECK-LABEL: define <2 x float> @same_lane_users(
; CHECK-SAME: <2 x float> [[A:%.*]], <2 x float> [[B:%.*]], <2 x float> [[C:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = extractelement <2 x float> [[A]], i64 0
; CHECK-NEXT:    [[TMP2:%.*]] = extractelement <2 x float> [[B]], i64 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x float> [[C]], i64 0
; CHECK-NEXT:    [[TMP4:%.*]] = call float @llvm.fma.f32(float [[TMP1]], float [[TMP2]], float [[TMP3]])
; CHECK-NEXT:    [[R0:%.*]] = insertelement <2 x float> poison, float [[TMP4]], i64 0
; CHECK-NEXT:    [[R1:%.*]] = insertelement <2 x float> [[R0]], float [[TMP4]], i64 1
; CHECK-NEXT:    ret <2 x float> [[R1]]
;
  %v = call <2 x float> @llvm.fma.v2f32(<2 x float> %a, <2 x float> %b, <2 x float> %c)
  %lo = extractelement <2 x float> %v, i64 0
  %again = extractelement <2 x float> %v, i64 0
  %r0 = insertelement <2 x float> poison, float %lo, i64 0
  %r1 = insertelement <2 x float> %r0, float %again, i64 1
  ret <2 x float> %r1
}

define <4 x float> @mixed_pairs(<4 x float> %a, <4 x float> %b, <4 x float> %c) {
; CHECK-LABEL: define <4 x float> @mixed_pairs(
; CHECK-SAME: <4 x float> [[A:%.*]], <4 x float> [[B:%.*]], <4 x float> [[C:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <4 x float> [[A]], <4 x float> poison, <2 x i32> <i32 0, i32 1>
; CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <4 x float> [[B]], <4 x float> poison, <2 x i32> <i32 0, i32 1>
; CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <4 x float> [[C]], <4 x float> poison, <2 x i32> <i32 0, i32 1>
; CHECK-NEXT:    [[TMP4:%.*]] = call <2 x float> @llvm.fma.v2f32(<2 x float> [[TMP1]], <2 x float> [[TMP2]], <2 x float> [[TMP3]])
; CHECK-NEXT:    [[TMP5:%.*]] = extractelement <2 x float> [[TMP4]], i64 0
; CHECK-NEXT:    [[TMP6:%.*]] = insertelement <4 x float> poison, float [[TMP5]], i64 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractelement <2 x float> [[TMP4]], i64 1
; CHECK-NEXT:    [[TMP8:%.*]] = insertelement <4 x float> [[TMP6]], float [[TMP7]], i64 1
; CHECK-NEXT:    [[TMP9:%.*]] = extractelement <4 x float> [[A]], i64 2
; CHECK-NEXT:    [[TMP10:%.*]] = extractelement <4 x float> [[B]], i64 2
; CHECK-NEXT:    [[TMP11:%.*]] = extractelement <4 x float> [[C]], i64 2
; CHECK-NEXT:    [[TMP12:%.*]] = call float @llvm.fma.f32(float [[TMP9]], float [[TMP10]], float [[TMP11]])
; CHECK-NEXT:    [[TMP13:%.*]] = insertelement <4 x float> [[TMP8]], float [[TMP12]], i64 2
; CHECK-NEXT:    [[R:%.*]] = shufflevector <4 x float> [[TMP13]], <4 x float> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 poison>
; CHECK-NEXT:    ret <4 x float> [[R]]
;
  %v = call <4 x float> @llvm.fma.v4f32(<4 x float> %a, <4 x float> %b, <4 x float> %c)
  %r = shufflevector <4 x float> %v, <4 x float> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 poison>
  ret <4 x float> %r
}

; The mixed add/sub shuffle computes one lane per pair
; in each arithmetic operation. Wider vectors must not hide the unused lanes.
define <4 x float> @alternating_add_sub(<4 x float> %a, <4 x float> %b) {
; CHECK-LABEL: define <4 x float> @alternating_add_sub(
; CHECK-SAME: <4 x float> [[A:%.*]], <4 x float> [[B:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = extractelement <4 x float> [[A]], i64 0
; CHECK-NEXT:    [[TMP2:%.*]] = extractelement <4 x float> [[B]], i64 0
; CHECK-NEXT:    [[TMP3:%.*]] = fsub float [[TMP1]], [[TMP2]]
; CHECK-NEXT:    [[TMP4:%.*]] = insertelement <4 x float> poison, float [[TMP3]], i64 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractelement <4 x float> [[A]], i64 2
; CHECK-NEXT:    [[TMP6:%.*]] = extractelement <4 x float> [[B]], i64 2
; CHECK-NEXT:    [[TMP7:%.*]] = fsub float [[TMP5]], [[TMP6]]
; CHECK-NEXT:    [[TMP8:%.*]] = insertelement <4 x float> [[TMP4]], float [[TMP7]], i64 2
; CHECK-NEXT:    [[TMP9:%.*]] = extractelement <4 x float> [[A]], i64 1
; CHECK-NEXT:    [[TMP10:%.*]] = extractelement <4 x float> [[B]], i64 1
; CHECK-NEXT:    [[TMP11:%.*]] = fadd float [[TMP9]], [[TMP10]]
; CHECK-NEXT:    [[TMP12:%.*]] = insertelement <4 x float> poison, float [[TMP11]], i64 1
; CHECK-NEXT:    [[TMP13:%.*]] = extractelement <4 x float> [[A]], i64 3
; CHECK-NEXT:    [[TMP14:%.*]] = extractelement <4 x float> [[B]], i64 3
; CHECK-NEXT:    [[TMP15:%.*]] = fadd float [[TMP13]], [[TMP14]]
; CHECK-NEXT:    [[TMP16:%.*]] = insertelement <4 x float> [[TMP12]], float [[TMP15]], i64 3
; CHECK-NEXT:    [[R:%.*]] = shufflevector <4 x float> [[TMP8]], <4 x float> [[TMP16]], <4 x i32> <i32 0, i32 5, i32 2, i32 7>
; CHECK-NEXT:    ret <4 x float> [[R]]
;
  %sub = fsub <4 x float> %a, %b
  %add = fadd <4 x float> %a, %b
  %r = shufflevector <4 x float> %sub, <4 x float> %add, <4 x i32> <i32 0, i32 5, i32 2, i32 7>
  ret <4 x float> %r
}

define float @fmuladd_high(<2 x float> %a, <2 x float> %b, <2 x float> %c) {
; CHECK-LABEL: define float @fmuladd_high(
; CHECK-SAME: <2 x float> [[A:%.*]], <2 x float> [[B:%.*]], <2 x float> [[C:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = extractelement <2 x float> [[A]], i64 1
; CHECK-NEXT:    [[TMP2:%.*]] = extractelement <2 x float> [[B]], i64 1
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x float> [[C]], i64 1
; CHECK-NEXT:    [[TMP4:%.*]] = call float @llvm.fmuladd.f32(float [[TMP1]], float [[TMP2]], float [[TMP3]])
; CHECK-NEXT:    ret float [[TMP4]]
;
  %v = call <2 x float> @llvm.fmuladd.v2f32(<2 x float> %a, <2 x float> %b, <2 x float> %c)
  %r = extractelement <2 x float> %v, i64 1
  ret float %r
}

define <2 x float> @fully_used(<2 x float> %a, <2 x float> %b, <2 x float> %c) {
; PTX-LABEL: fully_used(
; PTX: fma.rn.f32x2
; PTX: ret;
; CHECK-LABEL: define <2 x float> @fully_used(
; CHECK-SAME: <2 x float> [[A:%.*]], <2 x float> [[B:%.*]], <2 x float> [[C:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = call <2 x float> @llvm.fma.v2f32(<2 x float> [[A]], <2 x float> [[B]], <2 x float> [[C]])
; CHECK-NEXT:    ret <2 x float> [[R]]
;
  %v = call <2 x float> @llvm.fma.v2f32(<2 x float> %a, <2 x float> %b, <2 x float> %c)
  ret <2 x float> %v
}

define float @both_lanes(<2 x float> %a, <2 x float> %b, <2 x float> %c) {
; CHECK-LABEL: define float @both_lanes(
; CHECK-SAME: <2 x float> [[A:%.*]], <2 x float> [[B:%.*]], <2 x float> [[C:%.*]]) {
; CHECK-NEXT:    [[V:%.*]] = call <2 x float> @llvm.fma.v2f32(<2 x float> [[A]], <2 x float> [[B]], <2 x float> [[C]])
; CHECK-NEXT:    [[LO:%.*]] = extractelement <2 x float> [[V]], i64 0
; CHECK-NEXT:    [[HI:%.*]] = extractelement <2 x float> [[V]], i64 1
; CHECK-NEXT:    [[R:%.*]] = fadd float [[LO]], [[HI]]
; CHECK-NEXT:    ret float [[R]]
;
  %v = call <2 x float> @llvm.fma.v2f32(<2 x float> %a, <2 x float> %b, <2 x float> %c)
  %lo = extractelement <2 x float> %v, i64 0
  %hi = extractelement <2 x float> %v, i64 1
  %r = fadd float %lo, %hi
  ret float %r
}

define <2 x float> @both_shuffle_operands(<2 x float> %a, <2 x float> %b, <2 x float> %c) {
; CHECK-LABEL: define <2 x float> @both_shuffle_operands(
; CHECK-SAME: <2 x float> [[A:%.*]], <2 x float> [[B:%.*]], <2 x float> [[C:%.*]]) {
; CHECK-NEXT:    [[V:%.*]] = call <2 x float> @llvm.fma.v2f32(<2 x float> [[A]], <2 x float> [[B]], <2 x float> [[C]])
; CHECK-NEXT:    ret <2 x float> [[V]]
;
  %v = call <2 x float> @llvm.fma.v2f32(<2 x float> %a, <2 x float> %b, <2 x float> %c)
  %r = shufflevector <2 x float> %v, <2 x float> %v, <2 x i32> <i32 0, i32 3>
  ret <2 x float> %r
}

define float @dynamic_index(<2 x float> %a, <2 x float> %b, <2 x float> %c, i64 %index) {
; CHECK-LABEL: define float @dynamic_index(
; CHECK-SAME: <2 x float> [[A:%.*]], <2 x float> [[B:%.*]], <2 x float> [[C:%.*]], i64 [[INDEX:%.*]]) {
; CHECK-NEXT:    [[V:%.*]] = call <2 x float> @llvm.fma.v2f32(<2 x float> [[A]], <2 x float> [[B]], <2 x float> [[C]])
; CHECK-NEXT:    [[R:%.*]] = extractelement <2 x float> [[V]], i64 [[INDEX]]
; CHECK-NEXT:    ret float [[R]]
;
  %v = call <2 x float> @llvm.fma.v2f32(<2 x float> %a, <2 x float> %b, <2 x float> %c)
  %r = extractelement <2 x float> %v, i64 %index
  ret float %r
}

define half @half_lane(<2 x half> %a, <2 x half> %b, <2 x half> %c) {
; CHECK-LABEL: define half @half_lane(
; CHECK-SAME: <2 x half> [[A:%.*]], <2 x half> [[B:%.*]], <2 x half> [[C:%.*]]) {
; CHECK-NEXT:    [[V:%.*]] = call <2 x half> @llvm.fma.v2f16(<2 x half> [[A]], <2 x half> [[B]], <2 x half> [[C]])
; CHECK-NEXT:    [[R:%.*]] = extractelement <2 x half> [[V]], i64 0
; CHECK-NEXT:    ret half [[R]]
;
  %v = call <2 x half> @llvm.fma.v2f16(<2 x half> %a, <2 x half> %b, <2 x half> %c)
  %r = extractelement <2 x half> %v, i64 0
  ret half %r
}

define float @strict_fma(<2 x float> %a, <2 x float> %b, <2 x float> %c) strictfp {
; CHECK-LABEL: define float @strict_fma(
; CHECK-SAME: <2 x float> [[A:%.*]], <2 x float> [[B:%.*]], <2 x float> [[C:%.*]]) #[[ATTR2:[0-9]+]] {
; CHECK-NEXT:    [[V:%.*]] = call <2 x float> @llvm.experimental.constrained.fma.v2f32(<2 x float> [[A]], <2 x float> [[B]], <2 x float> [[C]], metadata !"round.dynamic", metadata !"fpexcept.strict")
; CHECK-NEXT:    [[R:%.*]] = extractelement <2 x float> [[V]], i64 0
; CHECK-NEXT:    ret float [[R]]
;
  %v = call <2 x float> @llvm.experimental.constrained.fma.v2f32(<2 x float> %a, <2 x float> %b, <2 x float> %c, metadata !"round.dynamic", metadata !"fpexcept.strict")
  %r = extractelement <2 x float> %v, i64 0
  ret float %r
}

define float @frozen_fma(<2 x float> %a, <2 x float> %b, <2 x float> %c) {
; CHECK-LABEL: define float @frozen_fma(
; CHECK-SAME: <2 x float> [[A:%.*]], <2 x float> [[B:%.*]], <2 x float> [[C:%.*]]) {
; CHECK-NEXT:    [[V:%.*]] = call <2 x float> @llvm.fma.v2f32(<2 x float> [[A]], <2 x float> [[B]], <2 x float> [[C]])
; CHECK-NEXT:    [[FROZEN:%.*]] = freeze <2 x float> [[V]]
; CHECK-NEXT:    [[R:%.*]] = extractelement <2 x float> [[FROZEN]], i64 0
; CHECK-NEXT:    ret float [[R]]
;
  %v = call <2 x float> @llvm.fma.v2f32(<2 x float> %a, <2 x float> %b, <2 x float> %c)
  %frozen = freeze <2 x float> %v
  %r = extractelement <2 x float> %frozen, i64 0
  ret float %r
}

; Retain multiply/add contraction after scalarizing the mixed-sign SLP bundle.
; Without also splitting the exclusively scalar-consumed multiplies, NVPTX
; emits separate multiplies and additions instead of the four useful FMAs.
define void @mixed_sign_fma(<4 x float> %arg0, float %arg1, float %arg2, float %arg3, i1 %arg4, ptr %arg5) {
; PTX-LABEL: mixed_sign_fma(
; PTX-NOT: fma.rn.f32x2
; PTX-COUNT-4: fma.rn.f32 {{%.*}}
; PTX-NOT: fma.
; PTX: ret;
; NOFUSE-LABEL: mixed_sign_fma(
; NOFUSE-NOT: fma.
; NOFUSE: ret;
; CHECK-LABEL: define void @mixed_sign_fma(
; CHECK-SAME: <4 x float> [[ARG0:%.*]], float [[ARG1:%.*]], float [[ARG2:%.*]], float [[ARG3:%.*]], i1 [[ARG4:%.*]], ptr [[ARG5:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = extractelement <4 x float> [[ARG0]], i64 0
; CHECK-NEXT:    [[TMP2:%.*]] = fmul float [[TMP1]], [[ARG1]]
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <4 x float> [[ARG0]], i64 1
; CHECK-NEXT:    [[TMP4:%.*]] = fmul float [[TMP3]], [[ARG1]]
; CHECK-NEXT:    [[TMP5:%.*]] = extractelement <4 x float> [[ARG0]], i64 2
; CHECK-NEXT:    [[TMP6:%.*]] = fmul float [[TMP5]], [[ARG1]]
; CHECK-NEXT:    [[TMP7:%.*]] = extractelement <4 x float> [[ARG0]], i64 3
; CHECK-NEXT:    [[TMP8:%.*]] = fmul float [[TMP7]], [[ARG1]]
; CHECK-NEXT:    [[TMP9:%.*]] = extractelement <4 x float> [[ARG0]], i64 0
; CHECK-NEXT:    [[TMP10:%.*]] = fmul float [[TMP9]], [[ARG2]]
; CHECK-NEXT:    [[TMP11:%.*]] = extractelement <4 x float> [[ARG0]], i64 1
; CHECK-NEXT:    [[TMP12:%.*]] = fmul float [[TMP11]], [[ARG2]]
; CHECK-NEXT:    [[TMP13:%.*]] = extractelement <4 x float> [[ARG0]], i64 2
; CHECK-NEXT:    [[TMP14:%.*]] = fmul float [[TMP13]], [[ARG2]]
; CHECK-NEXT:    [[TMP15:%.*]] = extractelement <4 x float> [[ARG0]], i64 3
; CHECK-NEXT:    [[TMP16:%.*]] = fmul float [[TMP15]], [[ARG2]]
; CHECK-NEXT:    [[TMP17:%.*]] = fsub float [[TMP2]], [[TMP12]]
; CHECK-NEXT:    [[TMP18:%.*]] = insertelement <4 x float> poison, float [[TMP17]], i64 0
; CHECK-NEXT:    [[TMP19:%.*]] = fsub float [[TMP6]], [[TMP16]]
; CHECK-NEXT:    [[TMP20:%.*]] = insertelement <4 x float> [[TMP18]], float [[TMP19]], i64 2
; CHECK-NEXT:    [[TMP21:%.*]] = fadd float [[TMP4]], [[TMP10]]
; CHECK-NEXT:    [[TMP22:%.*]] = insertelement <4 x float> poison, float [[TMP21]], i64 1
; CHECK-NEXT:    [[TMP23:%.*]] = fadd float [[TMP8]], [[TMP14]]
; CHECK-NEXT:    [[TMP24:%.*]] = insertelement <4 x float> [[TMP22]], float [[TMP23]], i64 3
; CHECK-NEXT:    [[V9:%.*]] = shufflevector <4 x float> [[TMP20]], <4 x float> [[TMP24]], <4 x i32> <i32 0, i32 5, i32 2, i32 7>
; CHECK-NEXT:    [[V10:%.*]] = insertelement <4 x float> poison, float [[ARG3]], i64 0
; CHECK-NEXT:    [[V11:%.*]] = shufflevector <4 x float> [[V10]], <4 x float> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[V12:%.*]] = fmul <4 x float> [[V9]], [[V11]]
; CHECK-NEXT:    [[V13:%.*]] = insertelement <4 x i1> poison, i1 [[ARG4]], i64 0
; CHECK-NEXT:    [[V14:%.*]] = shufflevector <4 x i1> [[V13]], <4 x i1> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[V15:%.*]] = select <4 x i1> [[V14]], <4 x float> [[V12]], <4 x float> zeroinitializer
; CHECK-NEXT:    [[V16:%.*]] = bitcast <4 x float> [[V15]] to <4 x i32>
; CHECK-NEXT:    [[V17:%.*]] = extractelement <4 x i32> [[V16]], i64 0
; CHECK-NEXT:    [[V18:%.*]] = extractelement <4 x i32> [[V16]], i64 1
; CHECK-NEXT:    [[V19:%.*]] = call <2 x i8> asm "cvt.rn.satfinite.e4m3x2.f32 $0, $2, $1;", "=h,r,r"(i32 [[V17]], i32 [[V18]])
; CHECK-NEXT:    store <2 x i8> [[V19]], ptr [[ARG5]], align 2
; CHECK-NEXT:    [[V20:%.*]] = extractelement <4 x i32> [[V16]], i64 2
; CHECK-NEXT:    [[V21:%.*]] = extractelement <4 x i32> [[V16]], i64 3
; CHECK-NEXT:    [[V22:%.*]] = call <2 x i8> asm "cvt.rn.satfinite.e4m3x2.f32 $0, $2, $1;", "=h,r,r"(i32 [[V20]], i32 [[V21]])
; CHECK-NEXT:    [[V23:%.*]] = getelementptr i8, ptr [[ARG5]], i64 2
; CHECK-NEXT:    store <2 x i8> [[V22]], ptr [[V23]], align 2
; CHECK-NEXT:    ret void
;
  %v0 = insertelement <4 x float> poison, float %arg1, i64 0
  %v1 = shufflevector <4 x float> %v0, <4 x float> poison, <4 x i32> zeroinitializer
  %v2 = fmul <4 x float> %arg0, %v1
  %v3 = insertelement <4 x float> poison, float %arg2, i64 0
  %v4 = shufflevector <4 x float> %v3, <4 x float> poison, <4 x i32> zeroinitializer
  %v5 = fmul <4 x float> %arg0, %v4
  %v6 = shufflevector <4 x float> %v5, <4 x float> poison, <4 x i32> <i32 1, i32 0, i32 3, i32 2>
  %v7 = fsub <4 x float> %v2, %v6
  %v8 = fadd <4 x float> %v2, %v6
  %v9 = shufflevector <4 x float> %v7, <4 x float> %v8, <4 x i32> <i32 0, i32 5, i32 2, i32 7>
  %v10 = insertelement <4 x float> poison, float %arg3, i64 0
  %v11 = shufflevector <4 x float> %v10, <4 x float> poison, <4 x i32> zeroinitializer
  %v12 = fmul <4 x float> %v9, %v11
  %v13 = insertelement <4 x i1> poison, i1 %arg4, i64 0
  %v14 = shufflevector <4 x i1> %v13, <4 x i1> poison, <4 x i32> zeroinitializer
  %v15 = select <4 x i1> %v14, <4 x float> %v12, <4 x float> zeroinitializer
  %v16 = bitcast <4 x float> %v15 to <4 x i32>
  %v17 = extractelement <4 x i32> %v16, i64 0
  %v18 = extractelement <4 x i32> %v16, i64 1
  %v19 = call <2 x i8> asm "cvt.rn.satfinite.e4m3x2.f32 $0, $2, $1;", "=h,r,r"(i32 %v17, i32 %v18)
  store <2 x i8> %v19, ptr %arg5, align 2
  %v20 = extractelement <4 x i32> %v16, i64 2
  %v21 = extractelement <4 x i32> %v16, i64 3
  %v22 = call <2 x i8> asm "cvt.rn.satfinite.e4m3x2.f32 $0, $2, $1;", "=h,r,r"(i32 %v20, i32 %v21)
  %v23 = getelementptr i8, ptr %arg5, i64 2
  store <2 x i8> %v22, ptr %v23, align 2
  ret void
}

; Do not duplicate a packed multiply that also has a whole-vector user.
define float @shared_multiply(<2 x float> %a, <2 x float> %b, <2 x float> %c, ptr %out) {
; CHECK-LABEL: define float @shared_multiply(
; CHECK-SAME: <2 x float> [[A:%.*]], <2 x float> [[B:%.*]], <2 x float> [[C:%.*]], ptr [[OUT:%.*]]) {
; CHECK-NEXT:    [[MUL:%.*]] = fmul <2 x float> [[A]], [[B]]
; CHECK-NEXT:    store <2 x float> [[MUL]], ptr [[OUT]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = extractelement <2 x float> [[MUL]], i64 0
; CHECK-NEXT:    [[TMP2:%.*]] = extractelement <2 x float> [[C]], i64 0
; CHECK-NEXT:    [[TMP3:%.*]] = fadd float [[TMP1]], [[TMP2]]
; CHECK-NEXT:    ret float [[TMP3]]
;
  %mul = fmul <2 x float> %a, %b
  store <2 x float> %mul, ptr %out
  %add = fadd <2 x float> %mul, %c
  %r = extractelement <2 x float> %add, i64 0
  ret float %r
}
