if(EXISTS "/Users/andrew/zzCoding-play/triton/build_unittest/unittest/Dialect/TritonGPU/LinearLayoutConversions[1]_tests.cmake")
  include("/Users/andrew/zzCoding-play/triton/build_unittest/unittest/Dialect/TritonGPU/LinearLayoutConversions[1]_tests.cmake")
else()
  add_test(LinearLayoutConversions_NOT_BUILT LinearLayoutConversions_NOT_BUILT)
endif()
