if(EXISTS "/Users/andrew/zzCoding-play/triton/build_unittest/unittest/Dialect/TritonGPU/TestSwizzling[1]_tests.cmake")
  include("/Users/andrew/zzCoding-play/triton/build_unittest/unittest/Dialect/TritonGPU/TestSwizzling[1]_tests.cmake")
else()
  add_test(TestSwizzling_NOT_BUILT TestSwizzling_NOT_BUILT)
endif()
